package main

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"logtheater/internal/alerts"
	"logtheater/internal/config"
	"logtheater/internal/domain"
	"logtheater/internal/emailconfig"
	"logtheater/internal/events"
	"logtheater/internal/executions"
	"logtheater/internal/monitoring"
	"logtheater/internal/repositories"
	settingsstore "logtheater/internal/settings"
)

const (
	demoDir    = "data"
	demoMarker = ".loghill-demo-data"
)

type senderSeed struct {
	ID, Name, Description string
	LastSeen              time.Duration
	LogCount              int
	Messages              []logMessage
}

type logMessage struct {
	Severity domain.LogSeverity
	Message  string
	Event    string
	Metadata map[string]any
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "populate demo data:", err)
		os.Exit(1)
	}
	fmt.Printf("LogHill demo data created in %s\n", demoDir)
}

func run() error {
	root, err := filepath.Abs(demoDir)
	if err != nil {
		return err
	}
	if filepath.Base(root) != "data" {
		return fmt.Errorf("refusing to replace unexpected directory %q", root)
	}
	marker := filepath.Join(root, demoMarker)
	if _, err = os.Stat(root); err == nil {
		if _, markerErr := os.Stat(marker); markerErr != nil {
			empty, checkErr := initialDataIsEmpty(root)
			if checkErr != nil {
				return checkErr
			}
			if !empty {
				return fmt.Errorf("%s contains application data and was not created by this command", demoDir)
			}
		} else {
			if err = os.RemoveAll(root); err != nil {
				return err
			}
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	if err = os.MkdirAll(root, 0o750); err != nil {
		return err
	}
	if err = os.WriteFile(marker, []byte("Generated by go run ./cmd/demo-data\n"), 0o640); err != nil {
		return err
	}

	now := time.Now().UTC().Truncate(time.Second)
	ctx := context.Background()
	repo := repositories.NewSenderRepository(root)
	if err = repo.Init(); err != nil {
		return err
	}
	if err = seedSenders(ctx, repo, now); err != nil {
		return err
	}
	if err = seedSettings(root, now); err != nil {
		return err
	}
	if err = seedEmailSettings(root, now); err != nil {
		return err
	}
	eventItems, err := seedEvents(root, now)
	if err != nil {
		return err
	}
	if err = seedAlerts(root, now); err != nil {
		return err
	}
	rules, err := seedMonitoring(root, now, eventItems)
	if err != nil {
		return err
	}
	return seedExecutions(root, now, rules, eventItems)
}

func initialDataIsEmpty(root string) (bool, error) {
	entries, err := os.ReadDir(filepath.Join(root, "senders"))
	if err == nil && len(entries) > 0 {
		return false, nil
	}
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return false, err
	}
	for _, path := range []string{"executions/executions.jsonl", "monitoring-executions.jsonl"} {
		info, statErr := os.Stat(filepath.Join(root, path))
		if statErr == nil && info.Size() > 0 {
			return false, nil
		}
		if statErr != nil && !errors.Is(statErr, os.ErrNotExist) {
			return false, statErr
		}
	}
	for path, collection := range map[string]string{"alerts.json": "items", "events.json": "events", "monitoring-rules.json": "rules"} {
		data, readErr := os.ReadFile(filepath.Join(root, path))
		if errors.Is(readErr, os.ErrNotExist) {
			continue
		}
		if readErr != nil {
			return false, readErr
		}
		var value map[string]json.RawMessage
		if json.Unmarshal(data, &value) != nil {
			return false, nil
		}
		var items []json.RawMessage
		if json.Unmarshal(value[collection], &items) != nil || len(items) > 0 {
			return false, nil
		}
	}
	return true, nil
}

func senderSeeds() []senderSeed {
	return []senderSeed{
		{ID: "checkout-api", Name: "Checkout API", Description: "Creates carts, validates inventory, and coordinates checkout sessions.", LastSeen: 45 * time.Second, LogCount: 42, Messages: []logMessage{
			{domain.Info, "Checkout session created for cart crt_89421", "", meta("route", "/v1/checkout", "region", "us-east-1", "duration_ms", 184)},
			{domain.Warn, "API response time exceeded 1200ms", "checkout_latency", meta("route", "/v1/checkout/confirm", "duration_ms", 1482, "trace_id", "trc_demo_7f21")},
			{domain.Info, "Inventory reservation confirmed for 3 items", "", meta("warehouse", "east-02", "cart_id", "crt_89421")},
			{domain.Debug, "Reusing cached shipping quote", "", meta("cache_age_ms", 4200, "carrier", "parcel-express")},
			{domain.Error, "Upstream pricing service returned 502", "", meta("upstream", "pricing-api", "attempt", 1)},
		}},
		{ID: "payment-worker", Name: "Payment Worker", Description: "Processes payment intents and reconciles transactions with providers.", LastSeen: 72 * time.Second, LogCount: 48, Messages: []logMessage{
			{domain.Info, "Payment successfully processed", "", meta("payment_id", "pay_demo_8421", "provider", "stripe-sandbox", "amount", 129.90)},
			{domain.Error, "Failed to process payment transaction", "payment_failed", meta("payment_id", "pay_demo_8477", "provider", "stripe-sandbox", "reason", "issuer_unavailable")},
			{domain.Debug, "Retrying provider request. Attempt 2/3", "", meta("payment_id", "pay_demo_8477", "backoff_ms", 800)},
			{domain.Warn, "Payment authorization took longer than expected", "", meta("duration_ms", 2160, "provider", "stripe-sandbox")},
			{domain.Info, "Settlement batch #8421 completed", "", meta("transactions", 186, "total", 28490.42)},
		}},
		{ID: "auth-service", Name: "Auth Service", Description: "Authenticates customers and issues short-lived access sessions.", LastSeen: 2 * time.Minute, LogCount: 34, Messages: []logMessage{
			{domain.Info, "Access token issued successfully", "", meta("grant_type", "authorization_code", "duration_ms", 96)},
			{domain.Warn, "Repeated invalid login attempts detected", "", meta("account_ref", "acct_demo_204", "attempts", 5)},
			{domain.Error, "Session signature validation failed", "", meta("reason", "expired_key_version", "key_version", 12)},
			{domain.Debug, "OIDC discovery document served from cache", "", meta("cache_hit", true)},
		}},
		{ID: "customer-api", Name: "Customer API", Description: "Manages customer profiles, addresses, and account preferences.", LastSeen: 4 * time.Minute, LogCount: 31, Messages: []logMessage{
			{domain.Info, "Customer profile updated", "", meta("customer_ref", "cus_demo_3318", "fields", []string{"phone", "locale"})},
			{domain.Error, "Connection refused while accessing PostgreSQL", "", meta("database", "customer-primary", "pool", "writer", "retryable", true)},
			{domain.Info, "Database connection pool recovered", "database_recovered", meta("database", "customer-primary", "available_connections", 18)},
			{domain.Warn, "Address validation provider is responding slowly", "", meta("duration_ms", 1870, "provider", "address-sandbox")},
		}},
		{ID: "notification-service", Name: "Notification Service", Description: "Delivers transactional email and customer notifications.", LastSeen: 11 * time.Minute, LogCount: 29, Messages: []logMessage{
			{domain.Info, "Order confirmation email queued", "", meta("template", "order-confirmation-v4", "channel", "email")},
			{domain.Warn, "Queue depth reached 78%", "", meta("queue", "transactional-email", "depth", 624)},
			{domain.Error, "ECONNRESET while calling external delivery service", "", meta("provider", "mail-sandbox", "attempt", 2)},
			{domain.Debug, "Notification deduplication key accepted", "", meta("dedupe_window_seconds", 300)},
		}},
		{ID: "document-processor", Name: "Document Processor", Description: "Extracts metadata and validates uploaded invoices and receipts.", LastSeen: 6 * time.Minute, LogCount: 27, Messages: []logMessage{
			{domain.Info, "Document processing completed in 842ms", "document_processed", meta("document_ref", "doc_demo_1288", "pages", 4, "duration_ms", 842)},
			{domain.Debug, "OCR confidence score calculated", "", meta("confidence", 0.982, "engine", "vision-sandbox")},
			{domain.Warn, "Document requires manual review", "", meta("document_ref", "doc_demo_1294", "reason", "low_contrast")},
			{domain.Info, "Invoice fields normalized", "", meta("currency", "USD", "line_items", 7)},
		}},
		{ID: "billing-worker", Name: "Billing Worker", Description: "Generates invoices and executes recurring billing workflows.", LastSeen: 9 * time.Hour, LogCount: 24, Messages: []logMessage{
			{domain.Info, "Worker started processing billing batch #219", "", meta("batch_id", 219, "accounts", 412)},
			{domain.Info, "Invoice generation completed", "", meta("generated", 408, "skipped", 4)},
			{domain.Warn, "Tax calculation fallback applied", "", meta("country", "US", "provider", "tax-sandbox")},
			{domain.Debug, "Recurring billing cursor persisted", "", meta("cursor", "demo-page-18")},
		}},
		{ID: "catalog-indexer", Name: "Catalog Indexer", Description: "Synchronizes product updates with the search index.", LastSeen: 26 * time.Hour, LogCount: 22, Messages: []logMessage{
			{domain.Info, "Product index refresh completed", "", meta("documents", 1842, "duration_ms", 4380)},
			{domain.Warn, "Search replica lag exceeded threshold", "", meta("lag_seconds", 42, "replica", "catalog-search-02")},
			{domain.Debug, "Index checkpoint committed", "", meta("checkpoint", "demo-7781")},
		}},
	}
}

func seedSenders(ctx context.Context, repo repositories.SenderRepository, now time.Time) error {
	for index, seed := range senderSeeds() {
		lastSeen := now.Add(-seed.LastSeen)
		created := now.AddDate(0, 0, -(35 + index*3))
		status := domain.StatusOnline
		if seed.LastSeen > 5*time.Minute {
			status = domain.StatusInactive
		}
		sender := domain.Sender{ID: seed.ID, Name: seed.Name, Description: seed.Description, Status: status, CreatedAt: created, UpdatedAt: lastSeen, LastActivityAt: timePointer(lastSeen)}
		if status == domain.StatusInactive {
			sender.InactiveAt = timePointer(lastSeen.Add(5 * time.Minute))
		}
		if err := repo.Create(ctx, sender); err != nil {
			return fmt.Errorf("create sender %s: %w", seed.ID, err)
		}
		instanceID := fmt.Sprintf("ins_%032x", index+1)
		instance := domain.SenderInstance{ID: instanceID, CreatedAt: created.Add(2 * time.Minute), LastActivityAt: timePointer(lastSeen), LastHealthcheckAt: timePointer(lastSeen), Status: status}
		if err := repo.RegisterInstance(ctx, seed.ID, instance); err != nil {
			return fmt.Errorf("register instance for %s: %w", seed.ID, err)
		}
		entries := buildLogs(seed, instanceID, now, index)
		var count, size int64
		for _, entry := range entries {
			nextCount, nextSize, appendErr := repo.Append(ctx, seed.ID, entry, domain.NumberUnitValue{Value: 10_000, Unit: domain.StorageLines})
			if appendErr != nil {
				return fmt.Errorf("append log for %s: %w", seed.ID, appendErr)
			}
			count, size = nextCount, nextSize
		}
		sender.LogLineCount, sender.LogFileSize = count, size
		sender.InstanceCount = 1
		if updateErr := repo.Update(ctx, sender); updateErr != nil {
			return updateErr
		}
	}
	return nil
}

func buildLogs(seed senderSeed, instanceID string, now time.Time, senderIndex int) []domain.LogEntry {
	entries := make([]domain.LogEntry, 0, seed.LogCount)
	for index := 0; index < seed.LogCount; index++ {
		message := seed.Messages[index%len(seed.Messages)]
		age := seed.LastSeen + time.Duration(index*17+senderIndex*3)*time.Minute
		if index > seed.LogCount*2/3 {
			age += time.Duration(index%3) * 12 * time.Hour
		}
		timestamp := now.Add(-age)
		metadata := cloneMap(message.Metadata)
		metadata["environment"] = "production-demo"
		metadata["instance"] = fmt.Sprintf("%s-%02d", seed.ID, senderIndex+1)
		entries = append(entries, domain.LogEntry{Timestamp: timestamp, ActivityAt: timestamp, SenderID: seed.ID, InstanceID: instanceID, Severity: message.Severity, Message: message.Message, Event: message.Event, EventOccurrenceID: occurrence(message.Event, index), Metadata: metadata})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Timestamp.Before(entries[j].Timestamp) })
	return entries
}

func seedSettings(root string, now time.Time) error {
	store, err := settingsstore.Open(root, now)
	if err != nil {
		return err
	}
	_, err = store.Update(domain.Settings{LogLimit: domain.NumberUnitValue{Value: 10_000, Unit: domain.StorageLines}, InactivePreservation: domain.NumberUnitValue{Value: 2_000, Unit: domain.StorageLines}, InactiveAfterSeconds: 300, DeleteInactiveDays: 14}, now)
	return err
}

func seedEmailSettings(root string, now time.Time) error {
	key := base64.StdEncoding.EncodeToString([]byte("loghill-public-demo-key-32-bytes"))
	if err := os.WriteFile(filepath.Join(root, "email-encryption.key"), []byte(key+"\n"), 0o600); err != nil {
		return err
	}
	store, err := emailconfig.Open(root, config.Config{EmailProvider: "gmail", EmailSettingsEncryptionKey: key}, now)
	if err != nil {
		return err
	}
	_, err = store.Update(emailconfig.Input{Provider: domain.EmailProviderGmail, Enabled: true, Gmail: emailconfig.GmailInput{Host: "smtp.gmail.com", Port: 587, Username: "platform-alerts@example.com", Password: "demo-password-not-valid", From: "platform-alerts@example.com", SenderName: "LogHill Platform Alerts"}}, now)
	return err
}

func seedAlerts(root string, now time.Time) error {
	store, err := alerts.Open(root)
	if err != nil {
		return err
	}
	sent, failed := domain.DeliverySent, domain.DeliveryFailed
	items := []domain.EmailAlert{
		{ID: "alert_payment_operations", Name: "Payment failures", SenderIDs: []string{"payment-worker"}, SenderNames: []string{"Payment Worker"}, Severities: []domain.LogSeverity{domain.Error, domain.Fatal}, Recipients: []string{"payments-oncall@example.com"}, Provider: domain.EmailProviderGmail, Enabled: true, CreatedAt: now.AddDate(0, 0, -28), UpdatedAt: now.Add(-2 * time.Hour), LastTriggeredAt: timePointer(now.Add(-7 * time.Minute)), LastDeliveryAt: timePointer(now.Add(-7 * time.Minute)), LastDeliveryStatus: &sent, DeliveryCount: 38},
		{ID: "alert_checkout_reliability", Name: "Checkout reliability", SenderIDs: []string{"checkout-api"}, SenderNames: []string{"Checkout API"}, Severities: []domain.LogSeverity{domain.Warn, domain.Error}, Recipients: []string{"commerce-platform@example.com"}, Provider: domain.EmailProviderGmail, Enabled: true, CreatedAt: now.AddDate(0, 0, -24), UpdatedAt: now.Add(-5 * time.Hour), LastTriggeredAt: timePointer(now.Add(-18 * time.Minute)), LastDeliveryAt: timePointer(now.Add(-18 * time.Minute)), LastDeliveryStatus: &sent, DeliveryCount: 21},
		{ID: "alert_authentication_security", Name: "Authentication security", SenderIDs: []string{"auth-service"}, SenderNames: []string{"Auth Service"}, Severities: []domain.LogSeverity{domain.Error, domain.Fatal}, Recipients: []string{"security-team@example.com"}, Provider: domain.EmailProviderGmail, Enabled: true, CreatedAt: now.AddDate(0, 0, -20), UpdatedAt: now.Add(-3 * time.Hour), LastTriggeredAt: timePointer(now.Add(-43 * time.Minute)), LastDeliveryAt: timePointer(now.Add(-43 * time.Minute)), LastDeliveryStatus: &failed, LastDeliveryError: stringPointer("Delivery provider temporarily unavailable"), DeliveryCount: 14, FailureCount: 1},
		{ID: "alert_platform_critical", Name: "Platform critical errors", SenderIDs: []string{"checkout-api", "payment-worker", "customer-api", "notification-service"}, SenderNames: []string{"Checkout API", "Payment Worker", "Customer API", "Notification Service"}, Severities: []domain.LogSeverity{domain.Fatal}, Recipients: []string{"platform-oncall@example.com"}, Provider: domain.EmailProviderGmail, Enabled: true, CreatedAt: now.AddDate(0, 0, -17), UpdatedAt: now.Add(-8 * time.Hour), LastTriggeredAt: timePointer(now.Add(-19 * time.Hour)), LastDeliveryAt: timePointer(now.Add(-19 * time.Hour)), LastDeliveryStatus: &sent, DeliveryCount: 5},
	}
	for _, item := range items {
		if err = store.Put(item); err != nil {
			return err
		}
	}
	return nil
}

func seedEvents(root string, now time.Time) ([]domain.EventDefinition, error) {
	store, err := events.Open(root)
	if err != nil {
		return nil, err
	}
	sent := domain.DeliverySent
	items := []domain.EventDefinition{
		{ID: "event_payment_failed", Name: "Payment failure detected", Key: "payment_failed", SenderIDs: []string{"payment-worker"}, ActionType: domain.EventActionEmail, Recipients: []string{"payments-oncall@example.com"}, SubjectTemplate: "Payment failure on {{sender.name}}", MessageTemplate: "A payment transaction failed. Review the provider response and retry history.", Enabled: true, CreatedAt: now.AddDate(0, 0, -26), UpdatedAt: now.Add(-2 * time.Hour), LastTriggeredAt: timePointer(now.Add(-7 * time.Minute)), LastDeliveryAt: timePointer(now.Add(-7 * time.Minute)), LastDeliveryStatus: &sent, TriggerCount: 34, DeliveryCount: 34},
		{ID: "event_checkout_latency", Name: "Checkout latency threshold exceeded", Key: "checkout_latency", SenderIDs: []string{"checkout-api"}, ActionType: domain.EventActionNone, Enabled: true, CreatedAt: now.AddDate(0, 0, -23), UpdatedAt: now.Add(-4 * time.Hour), LastTriggeredAt: timePointer(now.Add(-18 * time.Minute)), TriggerCount: 19},
		{ID: "event_database_recovered", Name: "Database connection recovered", Key: "database_recovered", SenderIDs: []string{"customer-api"}, ActionType: domain.EventActionNone, Enabled: true, CreatedAt: now.AddDate(0, 0, -18), UpdatedAt: now.Add(-6 * time.Hour), LastTriggeredAt: timePointer(now.Add(-41 * time.Minute)), TriggerCount: 7},
		{ID: "event_document_processed", Name: "Document processing completed", Key: "document_processed", SenderIDs: []string{"document-processor"}, ActionType: domain.EventActionNone, Enabled: true, CreatedAt: now.AddDate(0, 0, -15), UpdatedAt: now.Add(-9 * time.Hour), LastTriggeredAt: timePointer(now.Add(-52 * time.Minute)), TriggerCount: 86},
		{ID: "event_worker_inactive", Name: "Background worker inactive", Key: "worker_inactive", SenderIDs: []string{"billing-worker", "catalog-indexer", "notification-service"}, ActionType: domain.EventActionEmail, Recipients: []string{"platform-oncall@example.com"}, SubjectTemplate: "{{sender.name}} is inactive", MessageTemplate: "No recent activity was detected for this background service.", Enabled: true, CreatedAt: now.AddDate(0, 0, -12), UpdatedAt: now.Add(-10 * time.Hour), LastTriggeredAt: timePointer(now.Add(-2 * time.Hour)), LastDeliveryAt: timePointer(now.Add(-2 * time.Hour)), LastDeliveryStatus: &sent, TriggerCount: 11, DeliveryCount: 11},
	}
	for _, item := range items {
		if err = store.Put(item); err != nil {
			return nil, err
		}
	}
	return items, nil
}

func seedMonitoring(root string, now time.Time, eventItems []domain.EventDefinition) ([]monitoring.Rule, error) {
	store, err := monitoring.Open(root)
	if err != nil {
		return nil, err
	}
	eventID := map[string]string{}
	for _, event := range eventItems {
		eventID[event.Key] = event.ID
	}
	rules := []monitoring.Rule{
		rule("rule_payment_failures", "Payment failures", "Detects failed payment transactions and creates an operational event.", []string{"payment-worker"}, now.AddDate(0, 0, -25), 46, 1,
			[]monitoring.Condition{condition("payment-severity", monitoring.ConditionSeverity, "equals", meta("severity", "ERROR")), condition("payment-message", monitoring.ConditionMessage, "contains", meta("text", "payment"))},
			[]monitoring.Action{action("payment-event", monitoring.ActionEvent, meta("event_id", eventID["payment_failed"], "message", "Payment failure detected by monitoring", "severity", "ERROR"))}),
		rule("rule_database_connections", "Database connection failures", "Finds PostgreSQL connectivity failures in customer-facing services.", []string{"customer-api", "checkout-api"}, now.AddDate(0, 0, -22), 17, 0,
			[]monitoring.Condition{condition("db-message", monitoring.ConditionMessage, "contains", meta("text", "Connection refused"))},
			[]monitoring.Action{action("db-email", monitoring.ActionEmail, meta("recipients", []string{"platform-oncall@example.com"}, "subject", "Database connection failure", "message", "A production service cannot connect to PostgreSQL."))}),
		rule("rule_checkout_latency", "Checkout latency", "Tracks checkout responses that exceed the expected latency threshold.", []string{"checkout-api"}, now.AddDate(0, 0, -19), 29, 0,
			[]monitoring.Condition{condition("latency-message", monitoring.ConditionMessage, "contains", meta("text", "response time exceeded"))},
			[]monitoring.Action{action("latency-event", monitoring.ActionEvent, meta("event_id", eventID["checkout_latency"], "message", "Checkout latency threshold exceeded", "severity", "WARN"))}),
		rule("rule_auth_errors", "Critical authentication errors", "Escalates authentication errors to the security response team.", []string{"auth-service"}, now.AddDate(0, 0, -16), 12, 1,
			[]monitoring.Condition{condition("auth-severity", monitoring.ConditionSeverity, "equals", meta("severity", "ERROR"))},
			[]monitoring.Action{action("auth-email", monitoring.ActionEmail, meta("recipients", []string{"security-team@example.com"}, "subject", "Authentication error", "message", "A critical authentication error requires investigation."))}),
		rule("rule_inactive_workers", "Inactive background workers", "Creates an event when a production worker stops reporting activity.", []string{"billing-worker", "catalog-indexer", "notification-service"}, now.AddDate(0, 0, -11), 8, 0,
			[]monitoring.Condition{condition("worker-status", monitoring.ConditionSenderStatus, "became", meta("status", "inactive"))},
			[]monitoring.Action{action("worker-event", monitoring.ActionEvent, meta("event_id", eventID["worker_inactive"], "message", "Background worker became inactive", "severity", "WARN"))}),
	}
	for index := range rules {
		last := now.Add(-time.Duration(7+index*11) * time.Minute)
		rules[index].LastEvaluatedAt = timePointer(last)
		rules[index].LastExecutedAt = timePointer(last)
		rules[index].LastResult = "matched"
		if err = store.Put(rules[index]); err != nil {
			return nil, err
		}
	}
	return rules, nil
}

func seedExecutions(root string, now time.Time, rules []monitoring.Rule, eventItems []domain.EventDefinition) error {
	store, err := executions.Open(root, time.Now)
	if err != nil {
		return err
	}
	ruleNames := map[string]string{}
	for _, rule := range rules {
		ruleNames[rule.ID] = rule.Name
	}
	eventNames := map[string]string{}
	for _, event := range eventItems {
		eventNames[event.ID] = event.Name
	}
	stories := []struct {
		SourceType                                                                    executions.SourceType
		SourceID, SourceName, SenderID, SenderName, TriggerType, TriggerName, Message string
		Severity                                                                      domain.LogSeverity
		Status                                                                        executions.Status
	}{
		{executions.SourceMonitoring, "rule_payment_failures", ruleNames["rule_payment_failures"], "payment-worker", "Payment Worker", "log", "ERROR log", "Failed to process payment transaction", domain.Error, executions.StatusSuccess},
		{executions.SourceEvent, "event_payment_failed", eventNames["event_payment_failed"], "payment-worker", "Payment Worker", "event", "payment_failed", "Payment failure detected", domain.Error, executions.StatusSuccess},
		{executions.SourceAlert, "alert_payment_operations", "Payment failures", "payment-worker", "Payment Worker", "log", "ERROR log", "Failed to process payment transaction", domain.Error, executions.StatusSuccess},
		{executions.SourceMonitoring, "rule_checkout_latency", ruleNames["rule_checkout_latency"], "checkout-api", "Checkout API", "log", "WARN log", "API response time exceeded 1200ms", domain.Warn, executions.StatusSuccess},
		{executions.SourceEvent, "event_checkout_latency", eventNames["event_checkout_latency"], "checkout-api", "Checkout API", "event", "checkout_latency", "Checkout latency threshold exceeded", domain.Warn, executions.StatusSuccess},
		{executions.SourceMonitoring, "rule_database_connections", ruleNames["rule_database_connections"], "customer-api", "Customer API", "log", "ERROR log", "Connection refused while accessing PostgreSQL", domain.Error, executions.StatusSuccess},
		{executions.SourceEvent, "event_database_recovered", eventNames["event_database_recovered"], "customer-api", "Customer API", "event", "database_recovered", "Database connection pool recovered", domain.Info, executions.StatusSuccess},
		{executions.SourceMonitoring, "rule_auth_errors", ruleNames["rule_auth_errors"], "auth-service", "Auth Service", "log", "ERROR log", "Session signature validation failed", domain.Error, executions.StatusFailed},
		{executions.SourceAlert, "alert_authentication_security", "Authentication security", "auth-service", "Auth Service", "log", "ERROR log", "Session signature validation failed", domain.Error, executions.StatusFailed},
		{executions.SourceMonitoring, "rule_inactive_workers", ruleNames["rule_inactive_workers"], "billing-worker", "Billing Worker", "sender_status", "Sender inactive", "Background worker stopped reporting activity", domain.Warn, executions.StatusSuccess},
		{executions.SourceEvent, "event_document_processed", eventNames["event_document_processed"], "document-processor", "Document Processor", "event", "document_processed", "Document processing completed in 842ms", domain.Info, executions.StatusSuccess},
		{executions.SourceAlert, "alert_checkout_reliability", "Checkout reliability", "checkout-api", "Checkout API", "log", "WARN log", "API response time exceeded 1200ms", domain.Warn, executions.StatusSuccess},
	}
	for index := 0; index < 32; index++ {
		story := stories[index%len(stories)]
		started := now.Add(-time.Duration(3+index*8) * time.Minute)
		status := story.Status
		if index == 5 {
			status = executions.StatusProcessing
		}
		duration := int64(180 + (index%7)*93)
		finished := started.Add(time.Duration(duration) * time.Millisecond)
		record := executions.Record{ID: fmt.Sprintf("exec_demo_%03d", index+1), SourceType: story.SourceType, SourceID: story.SourceID, SourceName: story.SourceName, SenderID: story.SenderID, SenderName: story.SenderName, TriggerType: story.TriggerType, TriggerID: fmt.Sprintf("trigger_demo_%03d", index+1), TriggerName: story.TriggerName, TriggerMessage: story.Message, Severity: severityPointer(story.Severity), Status: status, CorrelationID: fmt.Sprintf("corr_demo_%04d", 8200+index), StartedAt: started, AttemptCount: 1, Actions: []executions.ActionResult{{ID: fmt.Sprintf("action_demo_%03d", index+1), Type: actionType(story.SourceType), Status: status, AttemptCount: 1}}, Conditions: []executions.ConditionResult{{ID: "condition-primary", Matched: status != executions.StatusFailed, Description: conditionDescription(story.SourceID)}}, Metadata: meta("environment", "production-demo")}
		if status != executions.StatusProcessing {
			record.FinishedAt = &finished
			record.DurationMs = &duration
		}
		if status == executions.StatusFailed {
			code, message := "DELIVERY_TEMPORARILY_UNAVAILABLE", "The demo delivery provider was temporarily unavailable."
			record.ErrorCode, record.ErrorMessage = &code, &message
			record.Actions[0].ErrorCode, record.Actions[0].ErrorMessage = &code, &message
		}
		if _, err = store.Create(record); err != nil {
			return err
		}
	}
	return nil
}

func rule(id, name, description string, senderIDs []string, created time.Time, count, failures int64, conditions []monitoring.Condition, actions []monitoring.Action) monitoring.Rule {
	nodes := make([]monitoring.ExpressionNode, len(conditions))
	for index := range conditions {
		connector := monitoring.LogicalAnd
		nodes[index] = monitoring.ExpressionNode{Connector: connector, Condition: &conditions[index]}
	}
	return monitoring.Rule{ID: id, Name: name, Description: description, SenderIDs: senderIDs, Expression: monitoring.ExpressionGroup{ID: id + "-expression", Operator: monitoring.LogicalAnd, Nodes: nodes}, Actions: actions, Enabled: true, Status: "active", CreatedAt: created, UpdatedAt: created.Add(24 * time.Hour), ExecutionCount: count, FailureCount: failures}
}

func condition(id string, kind monitoring.ConditionType, operator string, value map[string]any) monitoring.Condition {
	return monitoring.Condition{ID: id, Type: kind, Operator: operator, Value: raw(value)}
}

func action(id string, kind monitoring.ActionType, config map[string]any) monitoring.Action {
	return monitoring.Action{ID: id, Type: kind, Config: raw(config)}
}

func raw(value any) json.RawMessage {
	data, err := json.Marshal(value)
	if err != nil {
		panic(err)
	}
	return data
}

func meta(values ...any) map[string]any {
	result := make(map[string]any, len(values)/2)
	for index := 0; index+1 < len(values); index += 2 {
		result[fmt.Sprint(values[index])] = values[index+1]
	}
	return result
}

func cloneMap(value map[string]any) map[string]any {
	result := make(map[string]any, len(value)+2)
	for key, item := range value {
		result[key] = item
	}
	return result
}

func occurrence(event string, index int) string {
	if event == "" {
		return ""
	}
	return fmt.Sprintf("demo-%s-%03d", strings.ReplaceAll(event, "_", "-"), index+1)
}

func actionType(source executions.SourceType) string {
	if source == executions.SourceEvent {
		return "event"
	}
	return "send_email"
}

func conditionDescription(sourceID string) string {
	switch sourceID {
	case "rule_payment_failures":
		return "Severity equals ERROR and message contains payment"
	case "rule_checkout_latency":
		return "Message contains response time exceeded"
	case "rule_database_connections":
		return "Message contains Connection refused"
	case "rule_auth_errors":
		return "Severity equals ERROR"
	case "rule_inactive_workers":
		return "Sender status became inactive"
	default:
		return "Configured trigger matched"
	}
}

func timePointer(value time.Time) *time.Time                       { return &value }
func stringPointer(value string) *string                           { return &value }
func severityPointer(value domain.LogSeverity) *domain.LogSeverity { return &value }
