$ErrorActionPreference = 'Stop'

$pairs = @(
  @('Não foi possível carregar os eventos.', 'Unable to load events.'),
  @('Event desativado.', 'Event disabled.'),
  @('Event ativado.', 'Event enabled.'),
  @('Não foi possível alterar o evento.', 'Unable to update the event.'),
  @('Event excluído.', 'Event deleted.'),
  @('Não foi possível excluir o evento.', 'Unable to delete the event.'),
  @('Execute ações quando um log informar explicitamente uma chave de evento.', 'Run actions when a log explicitly provides an event key.'),
  @('E-mail não configurado', 'Email not configured'),
  @('Events podem ser salvos como inativos, mas só poderão ser ativados após configurar o provider.', 'Events can be saved as inactive, but can only be enabled after configuring the provider.'),
  @('E-mail pronto para executar eventos.', 'Email is ready to run events.'),
  @('configurados', 'configured'),
  @('aceitando disparos', 'accepting triggers'),
  @('nas últimas 24 horas', 'in the last 24 hours'),
  @('Events configurados', 'Configured events'),
  @('O matching usa a chave exata e os senders associados, independentemente da severity.', 'Matching uses the exact key and associated senders, regardless of severity.'),
  @('Filtrar por sender', 'Filter by sender'),
  @('Todos', 'All'),
  @('Crie uma ação explícita para ser chamada pelo parâmetro', 'Create an explicit action to be called by the'),
  @('dos seus logs.', 'parameter in your logs.'),
  @('Event salvo com sucesso.', 'Event saved successfully.'),
  @('O evento “${deleting.name}” e a chave ${deleting.key} serão removidos permanentemente.', 'The “${deleting.name}” event and the ${deleting.key} key will be permanently deleted.'),
  @('Excluir evento', 'Delete event'),
  @('Status do sender', 'Sender status'),
  @('Log recebido', 'Log received'),
  @('Horário', 'Time'),
  @('Grupo de condições', 'Condition group'),
  @('Fechar detalhes da regra', 'Close rule details'),
  @('Detalhes de ${rule.name}', 'Details for ${rule.name}'),
  @('Sem descrição', 'No description'),
  @('Expressão', 'Expression'),
  @('QUANDO', 'WHEN'),
  @('ENTÃO', 'THEN'),
  @('Ações', 'Actions'),
  @('Criada', 'Created'),
  @('Alterada', 'Updated'),
  @('Execuções', 'Executions'),
  @('Falhas', 'Failures'),
  @('Último erro', 'Last error'),
  @('Duplicar', 'Duplicate'),
  @('Desativar', 'Disable'),
  @('Ativar', 'Enable'),
  @('Editar', 'Edit'),
  @('Não foi possível carregar as regras.', 'Unable to load rules.'),
  @('Regra desativada.', 'Rule disabled.'),
  @('Regra ativada.', 'Rule enabled.'),
  @('Não foi possível alterar a regra.', 'Unable to update the rule.'),
  @('Não foi possível duplicar a regra.', 'Unable to duplicate the rule.'),
  @('Regra excluída.', 'Rule deleted.'),
  @('Não foi possível excluir a regra.', 'Unable to delete the rule.'),
  @('Crie fluxos automáticos combinando logs, eventos, horários e ações.', 'Create automated flows by combining logs, events, schedules, and actions.'),
  @('Nova regra', 'New rule'),
  @('Regras', 'Rules'),
  @('configuradas', 'configured'),
  @('Ativas', 'Active'),
  @('avaliando entradas', 'evaluating entries'),
  @('Execuções recentes', 'Recent executions'),
  @('Regras configuradas', 'Configured rules'),
  @('Buscar regra', 'Search rules'),
  @('Tipo de condição', 'Condition type'),
  @('Condições', 'Conditions'),
  @('Tipo de ação', 'Action type'),
  @('Status da regra', 'Rule status'),
  @('Inativas', 'Inactive'),
  @('Última execução', 'Last execution'),
  @('Ver detalhes', 'View details'),
  @('Editar regra', 'Edit rule'),
  @('Desativar regra', 'Disable rule'),
  @('Ativar regra', 'Enable rule'),
  @('Excluir regra', 'Delete rule'),
  @('Crie seu primeiro fluxo combinando condições e ações.', 'Create your first flow by combining conditions and actions.'),
  @('Draft salvo.', 'Draft saved.'),
  @('Excluir regra?', 'Delete rule?'),
  @('A regra “${deleting.name}” será removida. O histórico permanecerá disponível no arquivo de execuções.', 'The “${deleting.name}” rule will be deleted. Its history will remain available in the execution archive.'),
  @('Não foi possível carregar os alertas.', 'Unable to load alerts.'),
  @('Alert desativado.', 'Alert disabled.'),
  @('Alert ativado.', 'Alert enabled.'),
  @('Não foi possível alterar o alerta.', 'Unable to update the alert.'),
  @('Alert excluído.', 'Alert deleted.'),
  @('Não foi possível excluir o alerta.', 'Unable to delete the alert.'),
  @('Alerts de e-mail', 'Email alerts'),
  @('Configure regras de envio por sender e severity.', 'Configure delivery rules by sender and severity.'),
  @('Alerts podem ser salvos como inativos, mas só poderão ser ativados após configurar o provider.', 'Alerts can be saved as inactive, but can only be enabled after configuring the provider.'),
  @('E-mail pronto para enviar alertas.', 'Email is ready to send alerts.'),
  @('Alerts configurados', 'Configured alerts'),
  @('Buscar alerta, sender ou destinatário', 'Search alert, sender, or recipient'),
  @('Nenhum alerta configurado', 'No alerts configured'),
  @('Crie sua primeira regra para receber notificações por e-mail.', 'Create your first rule to receive email notifications.'),
  @('Alert salvo com sucesso.', 'Alert saved successfully.'),
  @('O alerta “${deleting.name}” será removido permanentemente.', 'The “${deleting.name}” alert will be permanently deleted.'),
  @('Excluir alerta', 'Delete alert'),
  @('Visão geral', 'Overview'),
  @('Saúde e volume dos serviços conectados.', 'Health and volume of connected services.'),
  @('Inventário de origens de logs registradas.', 'Inventory of registered log sources.'),
  @('Atualização', 'Refresh'),
  @('Intervalo de atualização', 'Refresh interval'),
  @('15 segundos', '15 seconds'),
  @('30 segundos', '30 seconds'),
  @('1 minuto', '1 minute'),
  @('Instâncias', 'Instances'),
  @('aguardando exclusão', 'awaiting deletion'),
  @('Total de logs', 'Total logs'),
  @('linhas armazenadas', 'stored lines'),
  @('Últimas 24h', 'Last 24h'),
  @('novas entradas', 'new entries'),
  @('Erros 24h', 'Errors 24h'),
  @('Fatais 24h', 'Fatal 24h'),
  @('Falhas 1h', 'Failures 1h'),
  @('Em andamento', 'In progress'),
  @('Refresh página', 'Refresh page'),
  @('Status, atividade e volume armazenado', 'Status, activity, and stored volume'),
  @('Últimas execuções', 'Latest executions'),
  @('Ver histórico', 'View history'),
  @('Nenhuma execução registrada.', 'No executions recorded.'),
  @('Não foi possível carregar os senders.', 'Unable to load senders.'),
  @('Mantém os últimos dados válidos quando uma atualização silenciosa falhar.', 'Keeps the latest valid data when a silent refresh fails.'),
  @('Não foi possível carregar o sender.', 'Unable to load the sender.'),
  @('Não foi possível carregar as instâncias.', 'Unable to load instances.'),
  @('Voltar para senders', 'Back to senders'),
  @('Instâncias de', 'Instances for'),
  @('Selecione qual execução do sender deseja visualizar.', 'Select which sender execution you want to view.'),
  @('instâncias identificadas', 'identified instances'),
  @('Instâncias registradas', 'Registered instances'),
  @('Cada linha representa uma inicialização independente do mesmo sender.', 'Each row represents an independent startup of the same sender.'),
  @('Ativos', 'Active'),
  @('Inativos', 'Inactive'),
  @('Instância', 'Instance'),
  @('Inicializada em', 'Started at'),
  @('Última atividade', 'Last activity'),
  @('Ações', 'Actions'),
  @('Nenhuma instância ativa.', 'No active instances.'),
  @('Nenhuma instância inativa.', 'No inactive instances.'),
  @('Excluir instância ${instance.id}', 'Delete instance ${instance.id}'),
  @('Excluir instância?', 'Delete instance?'),
  @('All logs da instância ${deletingInstance.id} serão excluídos permanentemente. O sender e as outras instâncias não serão alterados.', 'All logs from instance ${deletingInstance.id} will be permanently deleted. The sender and other instances will not be changed.'),
  @('A busca textual e a paginação precisam de uma lista estável. Pause o stream antes de continuar para que novos eventos não alterem os resultados durante a consulta.', 'Text search and pagination require a stable list. Pause the stream before continuing so new events do not change the results during the query.'),
  @('Status das instâncias', 'Instance status'),
  @('O valor deve ser um número inteiro.', 'The value must be an integer.'),
  @('Informe um número inteiro de ${unit}.', 'Enter an integer number of ${unit}.'),
  @('Configurações', 'Settings'),
  @('Abrir configurações', 'Open settings'),
  @('Use 0 para desativar o limite automático correspondente.', 'Use 0 to disable the corresponding automatic limit.'),
  @('Configuração legada acima de 10.000. Escolha um valor válido antes de salvar esta seção.', 'Legacy setting above 10,000. Choose a valid value before saving this section.'),
  @('A unidade foi alterada sem converter o valor. Revise o número antes de salvar.', 'The unit was changed without converting the value. Review the number before saving.'),
  @('Loading configurações', 'Loading settings'),
  @('Não foi possível carregar as configurações.', 'Unable to load settings.'),
  @('A quantidade preservada não pode ser maior que o limite máximo.', 'The retained amount cannot exceed the maximum limit.'),
  @('Não foi possível salvar as configurações.', 'Unable to save settings.'),
  @('Geral', 'General'),
  @('Consulte os valores atualmente aplicados e como as alterações entram em vigor.', 'Review the currently applied values and how changes take effect.'),
  @('Armazenamento de logs', 'Log storage'),
  @('Defina o limite máximo usado durante a gravação de novos logs.', 'Set the maximum limit used when writing new logs.'),
  @('Inatividade', 'Inactivity'),
  @('Defina quando um sender fica inativo, quanto preservar e quando excluir seus logs.', 'Set when a sender becomes inactive, how much to retain, and when to delete its logs.'),
  @('Configure o provedor usado para entregar os alertas de logs.', 'Configure the provider used to deliver log alerts.'),
  @('Fechar configurações', 'Close settings'),
  @('Configure os limites de armazenamento e compactação dos logs.', 'Configure log storage and compaction limits.'),
  @('Limite máximo atual', 'Current maximum limit'),
  @('Preservação após inatividade', 'Retention after inactivity'),
  @('As alterações salvas entram em vigor nos próximos ciclos de gravação e manutenção, sem reiniciar o LogHill.', 'Saved changes take effect during the next write and maintenance cycles without restarting LogHill.'),
  @('Limite máximo de logs', 'Maximum log limit'),
  @('Define o tamanho máximo do arquivo de logs de cada sender. Quando o limite for atingido, os registros mais antigos serão removidos primeiro.', 'Sets the maximum size of each sender log file. When the limit is reached, the oldest records are removed first.'),
  @('Quando o limite for atingido, os logs mais antigos serão removidos.', 'When the limit is reached, the oldest logs are removed.'),
  @('Sem limite: o arquivo poderá continuar crescendo enquanto o sender estiver ativo.', 'No limit: the file may continue growing while the sender is active.'),
  @('Considerar inativo após', 'Mark inactive after'),
  @('tempo de inatividade', 'inactivity duration'),
  @('Tempo sem logs ou healthcheck, em segundos.', 'Time without logs or health checks, in seconds.'),
  @('Excluir instâncias inativas após', 'Delete inactive instances after'),
  @('prazo de exclusão', 'deletion period'),
  @('Prazo contado a partir da inativação; a instância e seus logs serão removidos. Sem outras instâncias, o sender também desaparece.', 'Period counted from deactivation; the instance and its logs will be removed. If no other instances remain, the sender also disappears.'),
  @('Logs preservados após inatividade', 'Logs retained after inactivity'),
  @('Define quanto do histórico será mantido quando um sender for marcado como inativo.', 'Sets how much history is retained when a sender is marked inactive.'),
  @('Quando o sender ficar inativo, somente os registros mais recentes dentro deste limite serão mantidos.', 'When the sender becomes inactive, only the most recent records within this limit are retained.'),
  @('Nenhum log será preservado quando o sender ficar inativo.', 'No logs will be retained when the sender becomes inactive.'),
  @('Undo alterações', 'Undo changes'),
  @('Configurações salvas com sucesso.', 'Settings saved successfully.'),
  @('Restaurar padrões', 'Restore defaults'),
  @('Save alterações', 'Save changes'),
  @('Fechar confirmação e continuar editando', 'Close confirmation and continue editing'),
  @('Discard alterações?', 'Discard changes?'),
  @('As alterações feitas nesta janela ainda não foram salvas.', 'Changes made in this window have not been saved yet.'),
  @('Ações de ${sender.id}', 'Actions for ${sender.id}'),
  @('Editar informações', 'Edit information'),
  @('Escolha uma das ${group.items.length} instâncias', 'Choose one of ${group.items.length} instances'),
  @('Abrir instância ${sender.id}', 'Open instance ${sender.id}'),
  @('Abrir grupo ${group.name} com ${group.items.length} instâncias', 'Open ${group.name} group with ${group.items.length} instances'),
  @('instâncias conectadas a este sender', 'instances connected to this sender'),
  @('Voltar aos grupos', 'Back to groups'),
  @('Limpe os filtros ou escolha outro período.', 'Clear the filters or choose another period.'),
  @('Metadata', 'Metadata'),
  @('Identificador imutável', 'Immutable identifier'),
  @('O identificador aparecerá aqui', 'The identifier will appear here'),
  @('Identificador disponível', 'Identifier available'),
  @('Este identificador já está em uso. Escolha outro nome.', 'This identifier is already in use. Choose another name.'),
  @('Sender criado', 'Sender created'),
  @('O sender está pronto para receber conexões pelo nome.', 'The sender is ready to receive connections by name.'),
  @('Concluir', 'Done'),
  @('Descrição', 'Description'),
  @('Copiar configuração de ambiente', 'Copy environment configuration'),
  @('Copiar exemplo em Python', 'Copy Python example'),
  @('Configuração copiada.', 'Configuration copied.'),
  @('Não foi possível criar o sender.', 'Unable to create the sender.'),
  @('Novo sender', 'New sender'),
  @('Cadastre a origem antes de configurar o cliente que enviará os logs.', 'Register the source before configuring the client that will send logs.'),
  @('Criando...', 'Creating...'),
  @('Criar sender', 'Create sender'),
  @('Automação Financeira', 'Financial Automation'),
  @('Mínimo de 3 caracteres.', 'Minimum of 3 characters.'),
  @('(opcional)', '(optional)'),
  @('Processamento de boletos e acordos', 'Invoice and agreement processing'),
  @('Não foi possível concluir a operação.', 'Unable to complete the operation.'),
  @('Revoke acesso', 'Revoke access'),
  @('O identificador não pode ser alterado após a criação.', 'The identifier cannot be changed after creation.'),
  @('Processando...', 'Processing...'),
  @('Identificador', 'Identifier'),
  @('Nome de exibição', 'Display name'),
  @('Novas conexões serão bloqueadas e as credenciais das instâncias atuais deixarão de aceitar logs e healthchecks. Os dados e regras existentes serão preservados.', 'New connections will be blocked, and credentials for current instances will stop accepting logs and health checks. Existing data and rules will be preserved.'),
  @('O sender voltará a aceitar conexões pelo sender_name. Nenhuma chave precisa ser configurada nos clientes.', 'The sender will accept connections through sender_name again. No key needs to be configured in clients.'),
  @('Este sender está associado a ${dependencies.alert_rules} regra(s) de alerta, ${dependencies.events} evento(s) e ${dependencies.monitoring_rules} regra(s) de monitoramento. Ao continuar, ele será removido dessas configurações; as que ficarem sem senders serão desativadas.', 'This sender is associated with ${dependencies.alert_rules} alert rule(s), ${dependencies.events} event(s), and ${dependencies.monitoring_rules} monitoring rule(s). If you continue, it will be removed from those configurations; configurations left without senders will be disabled.'),
  @('Os logs e os dados deste sender serão excluídos permanentemente.', 'The sender logs and data will be permanently deleted.'),
  @('Não foi possível carregar as associações.', 'Unable to load associations.'),
  @('Não foi possível salvar as associações.', 'Unable to save associations.'),
  @('Fechar associações', 'Close associations'),
  @('Nenhum ${isAlerts ? "alerta" : "evento"} configurado', 'No ${isAlerts ? "alert" : "event"} configured'),
  @('Crie um na seção de ${label.toLowerCase()} para associá-lo aqui.', 'Create one in the ${label.toLowerCase()} section to associate it here.'),
  @('alteração${changed.length === 1 ? "" : "ões"}', 'change${changed.length === 1 ? "" : "s"}'),
  @('Save associações', 'Save associations'),
  @('Não foi possível enviar o teste.', 'Unable to send the test.'),
  @('Envie notificações por e-mail quando senders registrarem logs nas severidades selecionadas.', 'Send email notifications when senders record logs with the selected severities.'),
  @('monitorando logs', 'monitoring logs'),
  @('último envio falhou', 'last delivery failed'),
  @('Um e-mail é enviado para cada log que corresponder à regra.', 'An email is sent for each log that matches the rule.'),
  @('Níveis de log', 'Log levels'),
  @('Não foi possível buscar os senders.', 'Unable to search senders.'),
  @('obrigatório', 'required'),
  @('opcional', 'optional'),
  @('selecionado${value.length === 1 ? "" : "s"}', 'selected'),
  @('Select todos os resultados visíveis', 'Select all visible results'),
  @('Página anterior de senders', 'Previous sender page'),
  @('Página {page} de {totalPages}', 'Page {page} of {totalPages}'),
  @('Próxima página de senders', 'Next sender page'),
  @('Senders inativos podem ser monitorados, mas talvez não enviem novos logs.', 'Inactive senders can be monitored, but may not send new logs.'),
  @('Informe um endereço de e-mail válido.', 'Enter a valid email address.'),
  @('Este destinatário já foi adicionado.', 'This recipient has already been added.'),
  @('O limite é de 20 destinatários.', 'The limit is 20 recipients.'),
  @('Destinatários', 'Recipients'),
  @('Pressione Enter ou vírgula para adicionar.', 'Press Enter or comma to add.'),
  @('Última alteração', 'Last updated'),
  @('Último disparo', 'Last trigger'),
  @('Último envio', 'Last delivery'),
  @('Resultado', 'Result'),
  @('Adicione ao menos um destinatário.', 'Add at least one recipient.'),
  @('Não foi possível salvar o alerta.', 'Unable to save the alert.'),
  @('Fechar formulário', 'Close form'),
  @('Edit alerta', 'Edit alert'),
  @('New alert de e-mail', 'New email alert'),
  @('Cada log correspondente cria uma notificação individual.', 'Each matching log creates an individual notification.'),
  @('Fechar formulário de alerta', 'Close alert form'),
  @('Nenhum e-mail está configurado e habilitado.', 'No email provider is configured and enabled.'),
  @('Nome do alerta', 'Alert name'),
  @('Erros críticos da automação financeira', 'Critical errors in financial automation'),
  @('E-mail', 'Email'),
  @('Configurado', 'Configured'),
  @('Não configurado', 'Not configured'),
  @('Regra', 'Rule'),
  @('Níveis', 'Levels'),
  @('Never enviado', 'Never sent'),
  @('Informe um destinatário válido.', 'Enter a valid recipient.'),
  @('Fechar teste', 'Close test'),
  @('Usa o template de “{event.name}” com dados fictícios. O teste não conta como execução real.', 'Uses the “{event.name}” template with sample data. The test does not count as a real execution.'),
  @('Fechar teste do evento', 'Close event test'),
  @('Destinatário', 'Recipient'),
  @('usuario@empresa.com', 'user@company.com'),
  @('Enfileirando...', 'Queuing...'),
  @('processamento_finalizado', 'processing_completed'),
  @('Processamento finalizado', 'Processing completed'),
  @('automacao-financeira', 'financial-automation'),
  @('Processamento concluído com sucesso.', 'Processing completed successfully.'),
  @('metadata.protocolo', 'metadata.protocol'),
  @('metadata.destinatario', 'metadata.recipient'),
  @('metadata.chave', 'metadata.key'),
  @('cliente@empresa.com', 'customer@company.com'),
  @('valor de exemplo', 'sample value'),
  @('Prévia do e-mail', 'Email preview'),
  @('Subject do evento', 'Event subject'),
  @('Event do LogHill', 'LogHill event'),
  @('Nome do evento', 'Event name'),
  @('chave_do_evento', 'event_key'),
  @('A mensagem personalizada aparecerá aqui.', 'The custom message will appear here.'),
  @('Open logs do sender', 'Open sender logs'),
  @('Message do evento', 'Event message'),
  @('O processamento foi concluído.', 'Processing has completed.'),
  @('Protocolo:', 'Protocol:'),
  @('Variáveis disponíveis', 'Available variables'),
  @('Para metadata, substitua', 'For metadata, replace'),
  @('pelo nome enviado no log.', 'with the name sent in the log.'),
  @('Ação opcional', 'Optional action'),
  @('Enviar e-mail', 'Send email'),
  @('Desmarque para usar o evento somente em regras de Monitoring.', 'Clear this option to use the event only in monitoring rules.'),
  @('E-mail pronto para enviar.', 'Email is ready to send.'),
  @('Nenhum e-mail está configurado. O evento pode ser salvo somente como inativo.', 'No email provider is configured. The event can only be saved as inactive.'),
  @('Fechar detalhes', 'Close details'),
  @('Copiar chave', 'Copy key'),
  @('Não foi possível copiar.', 'Unable to copy.'),
  @('Ação', 'Action'),
  @('Nenhuma ação', 'No action'),
  @('Chave do evento', 'Event key'),
  @('Senders associados', 'Associated senders'),
  @('Último resultado', 'Last result'),
  @('A chave deve ter entre 3 e 80 caracteres e não pode conter espaços ou acentos.', 'The key must be between 3 and 80 characters and cannot contain spaces or accents.'),
  @('A chave é imutável depois da criação.', 'The key is immutable after creation.'),
  @('Chave disponível.', 'Key available.'),
  @('Use letras minúsculas, números, underscore ou hífen.', 'Use lowercase letters, numbers, underscores, or hyphens.'),
  @('A chave precisa estar disponível.', 'The key must be available.'),
  @('A mensagem deve ter até 10.000 caracteres.', 'The message must be at most 10,000 characters.'),
  @('Não foi possível salvar o evento.', 'Unable to save the event.'),
  @('Configuração gerenciada por variáveis de ambiente. Os campos ficam bloqueados, mas os testes permanecem disponíveis.', 'Configuration managed through environment variables. Fields are locked, but tests remain available.'),
  @('Habilitar envio por Outlook', 'Enable Outlook delivery'),
  @('Necessário para ativar novos alertas.', 'Required to enable new alerts.'),
  @('Credencial configurada — digite apenas para substituir', 'Credential configured — type only to replace it'),
  @('Informe a credencial', 'Enter the credential'),
  @('Ocultar credencial', 'Hide credential'),
  @('Mostrar credencial digitada', 'Show entered credential'),
  @('Credencial configurada. O valor salvo nunca é exibido.', 'Credential configured. The saved value is never displayed.'),
  @('SMTP / senha de aplicativo', 'SMTP / app password'),
  @('Disponível', 'Available'),
  @('Configuração gerenciada por variáveis de ambiente.', 'Configuration managed through environment variables.'),
  @('Usuário SMTP', 'SMTP username'),
  @('seuemail@gmail.com', 'your-email@gmail.com'),
  @('Senha de aplicativo', 'App password'),
  @('Senha configurada — digite apenas para substituir', 'Password configured — type only to replace it'),
  @('Senha de aplicativo do Google', 'Google app password'),
  @('Show password digitada', 'Show entered password'),
  @('Senha configurada. O valor salvo nunca é exibido.', 'Password configured. The saved value is never displayed.'),
  @('Não foi possível carregar a configuração de e-mail.', 'Unable to load email settings.'),
  @('Configuração de e-mail salva.', 'Email settings saved.'),
  @('Não foi possível salvar a configuração.', 'Unable to save settings.'),
  @('Informe o destinatário do teste.', 'Enter the test recipient.'),
  @('Validação e envio de teste', 'Validation and test delivery'),
  @('Valida a conexão do provedor selecionado. Para Gmail, use uma senha de aplicativo e SMTP com STARTTLS.', 'Validates the selected provider connection. For Gmail, use an app password and SMTP with STARTTLS.'),
  @('Testando...', 'Testing...'),
  @('Testar conexão', 'Test connection'),
  @('Destinatário do teste', 'Test recipient'),
  @('Enviando...', 'Sending...'),
  @('Permissão de envio necessária', 'Delivery permission required'),
  @('No Microsoft Entra, adicione', 'In Microsoft Entra, add'),
  @('e conceda o consentimento do administrador.', 'and grant administrator consent.'),
  @('Save configuração de e-mail', 'Save email settings'),
  @('Loading configuração de e-mail', 'Loading email settings'),
  @('Excluir instâncias inactive após', 'Delete inactive instances after'),
  @('Edit informações', 'Edit information'),
  @('Escolha uma das {group.items.length} instâncias', 'Choose one of {group.items.length} instances'),
  @('instâncias', 'instances'),
  @('Não foi possível carregar os logs.', 'Unable to load logs.'),
  @('Não foi possível excluir a instância.', 'Unable to delete the instance.'),
  @('Nenhuma instância {instanceStatusTab === "active" ? "ativa" : "inativa"}.', 'No {instanceStatusTab === "active" ? "active" : "inactive"} instances.'),
  @('Não disponível', 'Unavailable'),
  @('Excluir instância', 'Delete instance'),
  @('Excluindo...', 'Deleting...'),
  @('Confortável', 'Comfortable'),
  @('Presença de evento', 'Event presence'),
  @('Identifier imutável', 'Immutable identifier'),
  @('Identifier disponível', 'Identifier available'),
  @('Edit informações', 'Edit information'),
  @('Nenhum {isAlerts ? "alerta" : "evento"} configurado', 'No {isAlerts ? "alert" : "event"} configured'),
  @('Crie um na seção de {label.toLowerCase()} para associá-lo aqui.', 'Create one in the {label.toLowerCase()} section to associate it here.'),
  @('alteração{changed.length === 1 ? "" : "ões"}', 'change{changed.length === 1 ? "" : "s"}'),
  @('Ver todas as execuções', 'View all executions'),
  @('agora', 'now'),
  @('há ${minutes} min', '${minutes} min ago'),
  @('há ${hours} h', '${hours}h ago'),
  @('ontem', 'yesterday'),
  @('há ${days} dias', '${days}d ago'),
  @('Close details da execução', 'Close execution details'),
  @('Execução ${record.source_name}', '${record.source_name} execution'),
  @('Início', 'Started'),
  @('Término', 'Finished'),
  @('Gatilho', 'Trigger'),
  @('Conditions avaliadas', 'Evaluated conditions'),
  @('tentativa(s)', 'attempt(s)'),
  @('Código', 'Code'),
  @('Abrir sender', 'Open sender'),
  @('Não foi possível carregar as execuções.', 'Unable to load executions.'),
  @('Acompanhe resultados, tentativas e atividades recentes.', 'Track results, attempts, and recent activity.'),
  @('Buscar pelo nome da origem ou do sender', 'Search by source or sender name'),
  @('Refresh automática', 'Auto refresh'),
  @('Desativada', 'Disabled'),
  @('10 segundos', '10 seconds'),
  @('Execução', 'Execution'),
  @('Origem', 'Source'),
  @('Duração', 'Duration'),
  @('Nenhuma execução encontrada', 'No executions found'),
  @('Não existem execuções para o período e os filtros selecionados.', 'There are no executions for the selected period and filters.'),
  @('Identificação', 'Identification'),
  @('Revisão', 'Review'),
  @('O nome deve possuir entre 3 e 100 caracteres.', 'The name must be between 3 and 100 characters.'),
  @('Informe uma chave de evento válida.', 'Enter a valid event key.'),
  @('O limite é de 100 senders.', 'The limit is 100 senders.'),
  @('Configure um e-mail ou desative o envio de e-mail.', 'Configure email or disable email delivery.'),
  @('Informe o assunto do e-mail.', 'Enter the email subject.'),
  @('O assunto deve ter até 200 caracteres e não pode conter quebras de linha.', 'The subject must be at most 200 characters and cannot contain line breaks.'),
  @('Informe a mensagem do evento.', 'Enter the event message.'),
  @('Edit evento', 'Edit event'),
  @('Execute uma ação quando o cliente informar explicitamente esta chave no log.', 'Run an action when the client explicitly provides this key in a log.'),
  @('Close form de evento', 'Close event form'),
  @('Etapas do formulário', 'Form steps'),
  @('Email enviado com sucesso', 'Email sent successfully'),
  @('Nenhum template é necessário. Este evento será usado somente como gatilho no Monitoring.', 'No template is required. This event will only be used as a monitoring trigger.'),
  @('Nome', 'Name'),
  @('Chave', 'Key'),
  @('selecionado${senders.length === 1 ? "" : "s"}', 'selected'),
  @('endereço${recipients.length === 1 ? "" : "s"}', 'address${recipients.length === 1 ? "" : "es"}'),
  @('Não se aplica', 'Not applicable'),
  @('Somente Monitoring', 'Monitoring only'),
  @('Indisponível', 'Unavailable'),
  @('Desativado', 'Disabled'),
  @('Event ativo', 'Active event'),
  @('Inactive permanece salvo e não reage quando a chave for recebida.', 'An inactive event remains saved and does not react when the key is received.'),
  @('Configure o e-mail ou desative a ação de envio para salvar o evento ativo.', 'Configure email or disable the delivery action to save the active event.'),
  @('Voltar', 'Back'),
  @('Continuar', 'Continue'),
  @('Save evento', 'Save event'),
  @('Checking disponibilidade...', 'Checking availability...'),
  @('Esta chave já está em uso.', 'This key is already in use.'),
  @('Não foi possível verificar a chave.', 'Unable to check the key.'),
  @('Nenhuma execução', 'No executions'),
  @('Quando ${logical.map', 'When ${logical.map'),
  @('block.connector==="or"?"ou ":"e "', 'block.connector==="or"?"or ":"and "'),
  @('não ', 'not '),
  @('nenhum gatilho foi definido', 'no trigger was defined'),
  @('então ${actions.map', 'then ${actions.map'),
  @('nenhuma ação foi definida', 'no action was defined'),
  @('ECONNRESET durante o processamento', 'ECONNRESET during processing'),
  @('{"status":"teste"}', '{"status":"test"}'),
  @('Testar regra', 'Test rule'),
  @('Actions reais não serão executadas.', 'Real actions will not be executed.'),
  @('Close test da regra', 'Close rule test'),
  @('Sender de teste', 'Test sender'),
  @('Event de teste', 'Test event'),
  @('Severity de teste', 'Test severity'),
  @('Caminho percorrido', 'Evaluation path'),
  @('Result final:', 'Final result:'),
  @('avaliação pendente', 'evaluation pending'),
  @('regra seria executada', 'rule would run'),
  @('regra não executada', 'rule would not run'),
  @('Avaliando...', 'Evaluating...'),
  @('Avaliar regra', 'Evaluate rule'),
  @('Não foi possível carregar o construtor.', 'Unable to load the builder.'),
  @('Bloco ${blockSummary(block)} adicionado na posição ${result.blocks.length}.', '${blockSummary(block)} block added at position ${result.blocks.length}.'),
  @('Bloco movido para a posição ${from+direction+1} de ${blocks.length}.', 'Block moved to position ${from+direction+1} of ${blocks.length}.'),
  @('Bloco movido para a posição ${to+1} de ${blocks.length}.', 'Block moved to position ${to+1} of ${blocks.length}.'),
  @('Adição do bloco cancelada.', 'Block addition canceled.'),
  @('Alterações salvas.', 'Changes saved.'),
  @('Não foi possível salvar a regra.', 'Unable to save the rule.'),
  @('A metadata deve ser um objeto JSON válido.', 'Metadata must be a valid JSON object.'),
  @('Não foi possível testar a regra.', 'Unable to test the rule.'),
  @('Fechar construtor de monitoramento', 'Close monitoring builder'),
  @('Edit regra de monitoramento', 'Edit monitoring rule'),
  @('New rule de monitoramento', 'New monitoring rule'),
  @('Construa o fluxo arrastando condições e ações.', 'Build the flow by dragging conditions and actions.'),
  @('Fechar edição da regra', 'Close rule editor'),
  @('Fechar criação da regra', 'Close rule creation'),
  @('Nome da regra', 'Rule name'),
  @('A regra será ativada ao salvar', 'The rule will be enabled when saved'),
  @('Ativa ao salvar', 'Enabled on save'),
  @('Configuração', 'Configuration'),
  @('Posição', 'Position'),
  @('${problems.size} problema${problems.size===1?"":"s"} precisam ser corrigidos.', '${problems.size} issue${problems.size===1?"":"s"} must be fixed.'),
  @('Estrutura válida.', 'Valid structure.'),
  @('Save rascunho', 'Save draft'),
  @('Discard alterações', 'Discard changes'),
  @('As mudanças feitas no construtor serão perdidas.', 'Changes made in the builder will be lost.'),
  @('Seções', 'Sections'),
  @('segunda-feira', 'Monday'),
  @('terça-feira', 'Tuesday'),
  @('quarta-feira', 'Wednesday'),
  @('quinta-feira', 'Thursday'),
  @('sexta-feira', 'Friday'),
  @('sábado', 'Saturday'),
  @('domingo', 'Sunday'),
  @('contiver', 'contains'),
  @('not contains', 'does not contain'),
  @('for igual a', 'equals'),
  @('not for igual a', 'does not equal'),
  @('começar com', 'starts with'),
  @('terminar com', 'ends with'),
  @('not for', 'is not'),
  @('estiver em', 'is in'),
  @('not estiver em', 'is not in'),
  @('for disparado', 'is triggered'),
  @('not for disparado', 'is not triggered'),
  @('tiver sido disparado', 'was triggered'),
  @('not tiver sido disparado', 'was not triggered'),
  @('ficar', 'becomes'),
  @('existir', 'exists'),
  @('not existir', 'does not exist'),
  @('maior que', 'greater than'),
  @('maior ou igual a', 'greater than or equal to'),
  @('menor que', 'less than'),
  @('menor ou igual a', 'less than or equal to'),
  @('estiver entre', 'is between'),
  @('not estiver entre', 'is not between'),
  @('for depois de', 'is after'),
  @('for antes de', 'is before'),
  @('Mostrar configuração', 'Show configuration'),
  @('Selecione um bloco para configurá-lo.', 'Select a block to configure it.'),
  @('Configurar bloco', 'Configure block'),
  @('Ocultar configuração', 'Hide configuration'),
  @('Operador', 'Operator'),
  @('Operador da condição', 'Condition operator'),
  @('Selecione', 'Select'),
  @('Quando ficar', 'When it becomes'),
  @('Texto', 'Text'),
  @('Caminho', 'Path'),
  @('processo.numero', 'process.number'),
  @('Valor', 'Value'),
  @('Time inicial', 'Start time'),
  @('Time final', 'End time'),
  @('Weekday da semana', 'Weekday'),
  @('Inverter condição', 'Negate condition'),
  @('Exibe o marcador NÃO.', 'Displays the NOT marker.'),
  @('Event de destino', 'Target event'),
  @('Severity gerada', 'Generated severity'),
  @('suporte@empresa.com', 'support@company.com'),
  @('Prévia', 'Preview'),
  @('Sem assunto', 'No subject'),
  @('Sem mensagem', 'No message'),
  @('Variáveis:', 'Variables:'),
  @('Send test após salvar', 'Send test after saving'),
  @('Event disparado', 'Event triggered'),
  @('Inicia a regra por evento', 'Starts the rule from an event'),
  @('Alert disparado', 'Alert triggered'),
  @('Inicia a regra por alerta', 'Starts the rule from an alert'),
  @('Quando ficar...', 'When it becomes...'),
  @('Inicia quando o sender ficar ativo ou inativo', 'Starts when the sender becomes active or inactive'),
  @('Inicia a cada novo log', 'Starts on every new log'),
  @('Dados do log', 'Log data'),
  @('Message contém', 'Message contains'),
  @('Compara o texto do log', 'Compares the log text'),
  @('Filtra pelo nível do log', 'Filters by log level'),
  @('Consulta dados estruturados', 'Queries structured data'),
  @('Tempo', 'Time'),
  @('Compara uma faixa diária', 'Compares a daily time range'),
  @('Compara dias específicos', 'Compares specific weekdays'),
  @('Compara datas', 'Compares dates'),
  @('Usa o provider configurado', 'Uses the configured provider'),
  @('Disparar evento', 'Trigger event'),
  @('Aciona um evento existente', 'Triggers an existing event'),
  @('A regra já possui um gatilho inicial.', 'The rule already has an initial trigger.'),
  @('Adicione um gatilho antes das condições.', 'Add a trigger before conditions.'),
  @('Adicione um gatilho antes das ações.', 'Add a trigger before actions.'),
  @('Position inválida.', 'Invalid position.'),
  @('Actions devem permanecer depois das condições.', 'Actions must remain after conditions.'),
  @('Triggers e condições devem permanecer antes das ações.', 'Triggers and conditions must remain before actions.'),
  @('Selecione um evento.', 'Select an event.'),
  @('Selecione um alerta.', 'Select an alert.'),
  @('Informe o texto que deverá ser buscado.', 'Enter the text to search for.'),
  @('Informe o caminho da metadata.', 'Enter the metadata path.'),
  @('Selecione um evento de destino.', 'Select a target event.'),
  @('Selecione pelo menos um destinatário.', 'Select at least one recipient.'),
  @('Adicione um gatilho inicial.', 'Add an initial trigger.'),
  @('Adicione uma ação.', 'Add an action.'),
  @('not selecionado', 'not selected'),
  @('Quando ficar ${value.status==="inactive"?"inativo":"ativo"}', 'When it becomes ${value.status==="inactive"?"inactive":"active"}'),
  @('Quando qualquer log for recebido', 'When any log is received'),
  @(' e ${value.end}', ' and ${value.end}'),
  @('Send email para', 'Send email to'),
  @('destinatários not definidos', 'recipients not defined'),
  @('Disparar o evento', 'Trigger event'),
  @('E TAMBÉM', 'AND ALSO'),
  @('"OU"', '"OR"'),
  @('NÃO', 'NOT'),
  @('Soltar bloco aqui', 'Drop block here'),
  @('Arrastar ${blockTitle(block)}', 'Drag ${blockTitle(block)}'),
  @('GATILHO', 'TRIGGER'),
  @('AÇÃO', 'ACTION'),
  @('CONDIÇÃO', 'CONDITION'),
  @('Configurar', 'Configure'),
  @('Mover para cima', 'Move up'),
  @('Mover para baixo', 'Move down'),
  @('Remover', 'Remove'),
  @('Conector lógico', 'Logical connector'),
  @('INÍCIO', 'START'),
  @('Arraste um gatilho para começar', 'Drag a trigger to begin'),
  @('Escolha um bloco na biblioteca ou clique nele para adicionar.', 'Choose a block from the library or click it to add.'),
  @('FIM DO FLUXO', 'END OF FLOW'),
  @('Novos senders + ${value.length} selecionado${value.length===1?"":"s"}', 'New senders + ${value.length} selected'),
  @('All os novos senders', 'All new senders'),
  @('${value.length} sender${value.length===1?"":"s"} selecionado${value.length===1?"":"s"}', '${value.length} sender${value.length===1?"":"s"} selected'),
  @('Fechar seleção de senders', 'Close sender selection'),
  @('Select senders da regra', 'Select rule senders'),
  @('Fazer isso para todos os novos senders', 'Apply to all new senders'),
  @('Novos senders registrados serão adicionados automaticamente a esta regra.', 'Newly registered senders will be automatically added to this rule.'),
  @('Done seleção', 'Done'),
  @('Actions reais not serão executadas.', 'Real actions will not be executed.'),
  @('regra not executada', 'rule would not run'),
  @('useAppShell deve ser usado dentro de AppShell', 'useAppShell must be used within AppShell'),
  @('Os logs mais recentes aparecem embaixo', 'Newest logs appear at the bottom'),
  @('Os logs mais recentes aparecem no topo', 'Newest logs appear at the top'),
  @('Recentes embaixo', 'Newest at bottom'),
  @('Recentes no topo', 'Newest at top'),
  @('Ir para os logs mais recentes', 'Go to newest logs'),
  @('valor', 'value'),
  @('Buscar...', 'Search...'),
  @('Expirado', 'Expired'),
  @('Informe um valor entre 0 e 10.000.', 'Enter a value between 0 and 10,000.'),
  @('Informe um valor entre ${minimum.toLocaleString("en-US")} e ${maximum.toLocaleString("en-US")} ${unit}.', 'Enter a value between ${minimum.toLocaleString("en-US")} and ${maximum.toLocaleString("en-US")} ${unit}.'),
  @('segundos', 'seconds'),
  @('dias', 'days'),
  @('Settings salvas com sucesso.', 'Settings saved successfully.'),
  @('Executado em ${new Date(startedAt).toLocaleString("en-US")}', 'Executed at ${new Date(startedAt).toLocaleString("en-US")}'),
  @('RECENTE', 'RECENT'),
  @('Configure e habilite o provedor para ativar regras e enviar testes.', 'Configure and enable the provider to activate rules and send tests.'),
  @('Crie um alerta para receber por e-mail os erros enviados pelos seus senders.', 'Create an alert to receive sender errors by email.'),
  @('Close test do evento', 'Close event test'),
  @('Email remetente', 'Sender email'),
  @('logs@empresa.com', 'logs@company.com'),
  @('Name do remetente', 'Sender name'),
  @('Habilitar envio pelo Gmail', 'Enable Gmail delivery'),
  @('Usa SMTP com STARTTLS e senha de aplicativo.', 'Uses SMTP with STARTTLS and an app password.'),
  @('Servidor SMTP', 'SMTP server'),
  @('label="Porta"', 'label="Port"'),
  @('porta SMTP', 'SMTP port'),
  @('Errors recentes', 'Recent errors'),
  @('Nenhum sender encontrado', 'No senders found'),
  @('Tente alterar os filtros ou a busca.', 'Try changing the filters or search.'),
  @('Atividade', 'Activity'),
  @('Recipient do teste', 'Test recipient'),
  @('Disable evento', 'Disable event'),
  @('Enable evento', 'Enable event'),
  @('Enfileirado', 'Queued'),
  @('Enviado', 'Sent'),
  @('Falha', 'Failed'),
  @('Message enviada com sucesso', 'Message sent successfully'),
  @('Revise os dados do evento.', 'Review the event data.'),
  @('Email pronto para enviar.', 'Email is ready to send.'),
  @('Copiada', 'Copied'),
  @('Close details do evento', 'Close event details'),
  @('Copy key do evento', 'Copy event key'),
  @('Operator da condição', 'Condition operator'),
  @('Quando becomes', 'When it becomes'),
  @('Select um evento de destino.', 'Select a target event.'),
  @('Select um evento.', 'Select an event.'),
  @('Select um alerta.', 'Select an alert.'),
  @('Select pelo menos um destinatário.', 'Select at least one recipient.'),
  @('7 days', '7 days'),
  @('30 days', '30 days'),
  @('Personalizado', 'Custom'),
  @('Acompanhe resultados, attempt e atividades recentes.', 'Track results, attempts, and recent activity.'),
  @('Solte aqui para cancelar', 'Drop here to cancel'),
  @('Name da regra', 'Rule name'),
  @('Credencial inválida', 'Invalid credential'),
  @('O filtro enabled é inválido.', 'The enabled filter is invalid.'),
  @('O filtro severity é inválido.', 'The severity filter is invalid.'),
  @('O alerta está associado a regras de monitoramento.', 'The alert is associated with monitoring rules.'),
  @('O alerta não possui senders disponíveis.', 'The alert has no available senders.'),
  @('Não foi possível enfileirar o teste agora.', 'Unable to queue the test right now.'),
  @('Conexão com o provedor de e-mail validada com sucesso.', 'Email provider connection validated successfully.'),
  @('Informe um destinatário válido.', 'Enter a valid recipient.'),
  @('Alerta não encontrado.', 'Alert not found.'),
  @('Body inválido ou incompleto.', 'Invalid or incomplete request body.'),
  @('O body deve conter um único objeto JSON.', 'The request body must contain a single JSON object.'),
  @('O provedor de e-mail não está configurado.', 'The email provider is not configured.'),
  @('O serviço de e-mail não respondeu dentro do tempo esperado.', 'The email service did not respond within the expected time.'),
  @('Não foi possível concluir a operação com o provedor de e-mail.', 'Unable to complete the operation with the email provider.'),
  @('Body inválido', 'Invalid request body'),
  @('Senha inválida', 'Invalid password'),
  @('Não foi possível criar a sessão', 'Unable to create the session'),
  @('Regra de monitoramento não encontrada.', 'Monitoring rule not found.'),
  @('Confirme explicitamente a execução das ações.', 'Explicitly confirm action execution.'),
  @('O filtro action_type é inválido.', 'The action_type filter is invalid.'),
  @('O evento está associado a regras de monitoramento.', 'The event is associated with monitoring rules.'),
  @('O evento não possui senders disponíveis.', 'The event has no available senders.'),
  @('Evento não encontrado.', 'Event not found.'),
  @('Já existe um evento com esta chave.', 'An event with this key already exists.'),
  @('Período de execução inválido.', 'Invalid execution period.'),
  @('Execução não encontrada.', 'Execution not found.'),
  @('Filtros inválidos.', 'Invalid filters.'),
  @('Sender não encontrado', 'Sender not found'),
  @('Arquivo de log não está mais disponível', 'The log file is no longer available'),
  @('Severity inválida', 'Invalid severity'),
  @('O identificador do evento é inválido.', 'The event identifier is invalid.'),
  @('O identificador da ocorrência é inválido.', 'The occurrence identifier is invalid.'),
  @('Nome de sender inválido', 'Invalid sender name'),
  @('Já existe um sender com este identificador.', 'A sender with this identifier already exists.'),
  @('A chave informada não é válida para este sender.', 'The provided key is not valid for this sender.'),
  @('A credencial da instância é inválida. Inicialize uma nova instância.', 'The instance credential is invalid. Initialize a new instance.'),
  @('O sender está revogado. Gere uma nova chave ao reativá-lo.', 'The sender is revoked. Generate a new key when reactivating it.'),
  @('A operação não pode ser concluída no estado atual.', 'The operation cannot be completed in its current state.'),
  @('Operação cancelada', 'Operation canceled'),
  @('Já existe um sender com o identificador %s.', 'A sender with identifier %s already exists.'),
  @('O identificador informado é inválido.', 'The provided identifier is invalid.'),
  @('Formato inválido', 'Invalid format'),
  @('Streaming indisponível', 'Streaming unavailable'),
  @('Configurações inválidas ou incompletas.', 'Invalid or incomplete settings.'),
  @('Rota não encontrada', 'Route not found'),
  @('Limite de requisições excedido', 'Request limit exceeded'),
  @('ação de e-mail sem destinatários', 'email action without recipients'),
  @('tipo de ação de monitoramento inválido', 'invalid monitoring action type'),
  @('A chave do evento não pode ser alterada.', 'The event key cannot be changed.'),
  @('Selecione no máximo 100 senders.', 'Select at most 100 senders.'),
  @('Os senders devem ser válidos e não podem se repetir.', 'Senders must be valid and cannot be duplicated.'),
  @('O sender “%s” não está disponível.', 'Sender “%s” is not available.'),
  @('A ação selecionada não está disponível.', 'The selected action is not available.'),
  @('Informe de 1 a 20 destinatários.', 'Enter between 1 and 20 recipients.'),
  @('Informe apenas endereços de e-mail válidos.', 'Enter valid email addresses only.'),
  @('O assunto é obrigatório, deve ter até 200 caracteres e não pode conter quebras de linha.', 'The subject is required, must be at most 200 characters, and cannot contain line breaks.'),
  @('A mensagem é obrigatória e deve ter até 10.000 caracteres.', 'The message is required and must be at most 10,000 characters.'),
  @('A variável {{%s}} não é suportada.', 'The {{%s}} variable is not supported.'),
  @('Conclua o rascunho antes de ativá-lo.', 'Complete the draft before enabling it.'),
  @('Cópia de ', 'Copy of '),
  @('A descrição deve possuir no máximo 500 caracteres.', 'The description must be at most 500 characters.'),
  @('Status de regra inválido.', 'Invalid rule status.'),
  @('Um sender selecionado não existe.', 'A selected sender does not exist.'),
  @('Senders expirados ou revogados não podem ser monitorados.', 'Expired or revoked senders cannot be monitored.'),
  @('Adicione ao menos uma condição.', 'Add at least one condition.'),
  @('A regra excede os limites de condições ou grupos.', 'The rule exceeds the condition or group limits.'),
  @('Adicione entre 1 e 10 ações.', 'Add between 1 and 10 actions.'),
  @('O rascunho excede o limite de ações.', 'The draft exceeds the action limit.'),
  @('O rascunho excede o limite de condições.', 'The draft exceeds the condition limit.'),
  @('Use E ou OU para combinar as condições.', 'Use AND or OR to combine conditions.'),
  @('Um grupo não pode ficar vazio.', 'A group cannot be empty.'),
  @('Cada bloco deve conter uma condição ou grupo.', 'Each block must contain a condition or group.'),
  @('configuração vazia', 'empty configuration'),
  @('O operador não é compatível com a condição.', 'The operator is not compatible with the condition.'),
  @('Preencha os valores da condição.', 'Fill in the condition values.'),
  @('Preencha a configuração da ação.', 'Fill in the action configuration.'),
  @('O evento não é compatível com os senders da regra.', 'The event is not compatible with the rule senders.'),
  @('Configure um e-mail antes de ativar esta ação.', 'Configure email before enabling this action.'),
  @('Informe entre 1 e 20 destinatários.', 'Enter between 1 and 20 recipients.'),
  @('Existe um destinatário de e-mail inválido.', 'There is an invalid email recipient.'),
  @('Informe um assunto válido, sem quebras de linha.', 'Enter a valid subject without line breaks.'),
  @('Tipo de ação inválido.', 'Invalid action type.'),
  @('A ação cria um ciclo direto ou indireto entre eventos e regras.', 'The action creates a direct or indirect cycle between events and rules.'),
  @('"Quando " + strings.Join(parts, " e ") + ", então " + strings.Join(actions, " e ") + "."', '"When " + strings.Join(parts, " and ") + ", then " + strings.Join(actions, " and ") + "."'),
  @('"NÃO "', '"NOT "'),
  @('"o horário "', '"the time "'),
  @('"condição"', '"condition"'),
  @('Sender não encontrado.', 'Sender not found.'),
  @('O sender não pertence ao escopo da regra.', 'The sender is outside the rule scope.'),
  @('executor de ações indisponível', 'action executor unavailable'),
  @('Os identificadores dos senders são obrigatórios.', 'Sender identifiers are required.'),
  @('Um sender não pode ser selecionado mais de uma vez.', 'A sender cannot be selected more than once.'),
  @('O sender “%s” não está mais disponível.', 'Sender “%s” is no longer available.'),
  @('Uma das severidades é inválida.', 'One of the severities is invalid.'),
  @('Não foi possível ler a configuração segura do Outlook.', 'Unable to read the secure Outlook configuration.'),
  @('O Outlook não respondeu à tentativa de envio.', 'Outlook did not respond to the delivery attempt.'),
  @('O Outlook autenticou, mas não autorizou o envio. Conceda a permissão de aplicativo Mail.Send com consentimento administrativo e confirme que a mailbox remetente está no escopo permitido do Exchange.', 'Outlook authenticated but did not authorize delivery. Grant the Mail.Send application permission with administrator consent and confirm that the sender mailbox is within the allowed Exchange scope.'),
  @('A mailbox remetente não foi encontrada no Microsoft 365. Confirme o e-mail e se ele possui uma caixa do Exchange Online.', 'The sender mailbox was not found in Microsoft 365. Confirm the email address and that it has an Exchange Online mailbox.'),
  @('A mensagem de e-mail contém cabeçalhos inválidos.', 'The email message contains invalid headers.'),
  @('A mensagem possui um destinatário inválido.', 'The message has an invalid recipient.'),
  @('O Microsoft 365 não respondeu dentro do tempo esperado.', 'Microsoft 365 did not respond within the expected time.'),
  @('Não foi possível autenticar no Microsoft 365.', 'Unable to authenticate with Microsoft 365.'),
  @('A resposta de autenticação do Microsoft 365 é inválida.', 'The Microsoft 365 authentication response is invalid.'),
  @('As credenciais são válidas, mas o aplicativo não possui a permissão de aplicativo Mail.Send no token. Adicione a permissão no Microsoft Graph e conceda o consentimento do administrador.', 'The credentials are valid, but the application token does not include the Mail.Send application permission. Add the permission in Microsoft Graph and grant administrator consent.'),
  @('Provedor de e-mail inválido.', 'Invalid email provider.'),
  @('A configuração do Outlook é gerenciada por variáveis de ambiente.', 'The Outlook configuration is managed through environment variables.'),
  @('O nome do remetente contém caracteres inválidos.', 'The sender name contains invalid characters.'),
  @('Informe um e-mail remetente válido.', 'Enter a valid sender email address.'),
  @('O nome do remetente deve possuir no máximo 100 caracteres.', 'The sender name must be at most 100 characters.'),
  @('A configuração SMTP é gerenciada por variáveis de ambiente.', 'The SMTP configuration is managed through environment variables.'),
  @('Informe uma porta SMTP válida.', 'Enter a valid SMTP port.'),
  @('A configuração SMTP contém caracteres inválidos.', 'The SMTP configuration contains invalid characters.'),
  @('Complete o servidor, usuário, senha de aplicativo e remetente antes de habilitar o Gmail.', 'Complete the server, username, app password, and sender before enabling Gmail.'),
  @('O Gmail recusou um dos destinatários.', 'Gmail rejected one of the recipients.'),
  @('O Gmail recusou o início do envio.', 'Gmail rejected the start of delivery.'),
  @('Não foi possível enviar a mensagem pelo Gmail.', 'Unable to send the message through Gmail.'),
  @('Não foi possível conectar ao servidor SMTP do Gmail.', 'Unable to connect to the Gmail SMTP server.'),
  @('O servidor SMTP do Gmail retornou uma resposta inválida.', 'The Gmail SMTP server returned an invalid response.'),
  @('O servidor SMTP não oferece STARTTLS.', 'The SMTP server does not offer STARTTLS.'),
  @('Não foi possível estabelecer uma conexão segura com o Gmail.', 'Unable to establish a secure connection to Gmail.'),
  @('O Gmail recusou as credenciais. Use uma senha de aplicativo válida.', 'Gmail rejected the credentials. Use a valid app password.'),
  @('O servidor SMTP do Gmail não respondeu dentro do tempo esperado.', 'The Gmail SMTP server did not respond within the expected time.'),
  @('Este sender está associado a %d regras de alerta e %d eventos.', 'This sender is associated with %d alert rules and %d events.'),
  @('Este sender está associado a %d regras de alerta.', 'This sender is associated with %d alert rules.'),
  @('Este sender está associado a %d eventos.', 'This sender is associated with %d events.'),
  @('A fila de notificações está cheia; o log foi preservado, mas o e-mail não foi enfileirado.', 'The notification queue is full; the log was preserved, but the email was not queued.'),
  @('A fila de notificações está cheia.', 'The notification queue is full.'),
  @('O nome não gera um identificador válido.', 'The name does not produce a valid identifier.'),
  @('A descrição deve possuir no máximo 250 caracteres.', 'The description must be at most 250 characters.'),
  @('Unidade inválida.', 'Invalid unit.'),
  @('Mensagem fictícia de teste do evento LogHill.', 'Sample LogHill event test message.'),
  @('cliente@exemplo.com', 'customer@example.com'),
  @('destinatario', 'recipient'),
  @('protocolo', 'protocol'),
  @('TESTE-123', 'TEST-123'),
  @('A regra “%s” encontrou um novo registro que merece sua atenção.', 'Rule “%s” found a new record that requires your attention.'),
  @('Este é um envio de teste da regra “%s”. Nenhuma ocorrência real foi registrada.', 'This is a test delivery for rule “%s”. No real occurrence was recorded.'),
  @('Este é um teste do evento “%s”. Nenhuma ocorrência real foi registrada.', 'This is a test for event “%s”. No real occurrence was recorded.'),
  @('A integração do LogHill com o Outlook está funcionando e pronta para entregar seus alertas.', 'The LogHill integration with Outlook is working and ready to deliver your alerts.'),
  @('A integração do LogHill com o Gmail está funcionando e pronta para entregar seus alertas.', 'The LogHill integration with Gmail is working and ready to deliver your alerts.'),
  @('Configuração de e-mail', 'Email configuration'),
  @('Configuração validada', 'Configuration validated'),
  @('SUCESSO', 'SUCCESS'),
  @('Teste de e-mail do LogHill — configuração concluída', 'LogHill email test — configuration complete'),
  @('02/01/2006 às 15:04:05 MST', '01/02/2006 03:04:05 PM MST'),
  @('Novo diagnóstico disponível', 'New diagnostics available'),
  @('Diagnóstico registrado', 'Diagnostics recorded'),
  @('Nova informação registrada', 'New information recorded'),
  @('Informação registrada', 'Information recorded'),
  @('Um evento precisa de atenção', 'An event requires attention'),
  @('Atenção necessária', 'Attention required'),
  @('Uma falha crítica foi detectada', 'A critical failure was detected'),
  @('Falha crítica detectada', 'Critical failure detected'),
  @('Falha interna ao preparar a notificação.', 'Internal failure while preparing the notification.'),
  @('Não foi possível renderizar o e-mail.', 'Unable to render the email.'),
  @('O provedor Outlook não está configurado ou habilitado.', 'The Outlook provider is not configured or enabled.'),
  @('Integração', 'Integration'),
  @('Identificador', 'Identifier'),
  @('Horário do log', 'Log time'),
  @('Você recebeu este e-mail porque uma notificação foi configurada no LogHill.', 'You received this email because a notification was configured in LogHill.'),
  @('Os identificadores dos senders são requireds.', 'Sender identifiers are required.'),
  @('O sender “%s” not está mais disponível.', 'Sender “%s” is no longer available.'),
  @('Arquivo de log not está mais disponível', 'The log file is no longer available'),
  @('Name de sender inválido', 'Invalid sender name'),
  @('A chave informada not é válida para este sender.', 'The provided key is not valid for this sender.'),
  @('A operação not pode ser concluída no estado atual.', 'The operation cannot be completed in its current state.'),
  @('Settings inválidas ou incompletas.', 'Invalid or incomplete settings.'),
  @('O alerta not possui senders disponíveis.', 'The alert has no available senders.'),
  @('Não foi possível enfileirar o teste now.', 'Unable to queue the test right now.'),
  @('O provedor de e-mail not está configurado.', 'The email provider is not configured.'),
  @('O serviço de e-mail not respondeu dentro do tempo esperado.', 'The email service did not respond within the expected time.'),
  @('O evento not possui senders disponíveis.', 'The event has no available senders.'),
  @('Select no máximo 100 senders.', 'Select at most 100 senders.'),
  @('Os senders devem ser válidos e not podem se repetir.', 'Senders must be valid and cannot be duplicated.'),
  @('O sender “%s” not está disponível.', 'Sender “%s” is not available.'),
  @('A ação selecionada not está disponível.', 'The selected action is not available.'),
  @('O assunto é required, deve ter até 200 caracteres e not pode conter quebras de linha.', 'The subject is required, must be at most 200 characters, and cannot contain line breaks.'),
  @('A variável {{%s}} not é suportada.', 'The {{%s}} variable is not supported.'),
  @('O operador not é compatível com a condição.', 'The operator is not compatible with the condition.'),
  @('Preencha os valuees da condição.', 'Fill in the condition values.'),
  @('O evento not é compatível com os senders da regra.', 'The event is not compatible with the rule senders.'),
  @('Action type inválido.', 'Invalid action type.'),
  @('O nome not gera um identificador válido.', 'The name does not produce a valid identifier.'),
  @('O Outlook not respondeu à tentativa de envio.', 'Outlook did not respond to the delivery attempt.'),
  @('O Outlook autenticou, mas not autorizou o envio. Conceda a permissão de aplicativo Mail.Send com consentimento administrativo e confirme que a mailbox remetente está no escopo permitido do Exchange.', 'Outlook authenticated but did not authorize delivery. Grant the Mail.Send application permission with administrator consent and confirm that the sender mailbox is within the allowed Exchange scope.'),
  @('As credenciais são válidas, mas o aplicativo not possui a permissão de aplicativo Mail.Send no token. Adicione a permissão no Microsoft Graph and grant administrator consent.', 'The credentials are valid, but the application token does not include the Mail.Send application permission. Add the permission in Microsoft Graph and grant administrator consent.'),
  @('Informe uma SMTP port válida.', 'Enter a valid SMTP port.'),
  @('A fila de notificações está cheia; o log foi preservado, mas o e-mail not foi enfileirado.', 'The notification queue is full; the log was preserved, but the email was not queued.'),
  @('Failed interna ao preparar a notificação.', 'Internal failure while preparing the notification.'),
  @('O provedor Outlook not está configurado ou habilitado.', 'The Outlook provider is not configured or enabled.'),
  @('Failed crítica detectada', 'Critical failure detected'),
  @('Excluir', 'Delete'),
  @('Close details do alerta', 'Close alert details'),
  @('Close form de alerta', 'Close alert form'),
  @('Configure e habilite um e-mail ou salve o alerta como inativo.', 'Configure and enable email or save the alert as inactive.'),
  @('Save alerta', 'Save alert'),
  @('Failed ao enviar', 'Delivery failed'),
  @('Disable alerta', 'Disable alert'),
  @('Enable alerta', 'Enable alert'),
  @('Adicionar outro e-mail', 'Add another email'),
  @('Limpar ${label}', 'Clear ${label}'),
  @('Sucesso', 'Success'),
  @('Buscar bloco', 'Search blocks'),
  @('Configure um e-mail antes de usar este bloco.', 'Configure email before using this block.'),
  @('Inicia quando o sender becomes ativo ou inativo', 'Starts when the sender becomes active or inactive'),
  @('Mostrar biblioteca de blocos', 'Show block library'),
  @('${item.description}. Arraste ou pressione Enter para adicionar.', '${item.description}. Drag it or press Enter to add.'),
  @('A regra {{rule.name}} foi atendida para {{sender.name}}.', 'Rule {{rule.name}} matched for {{sender.name}}.'),
  @('Rule de monitoramento atendida', 'Monitoring rule matched'),
  @('${value.status==="inactive"?"inativo":"ativo"}', '${value.status==="inactive"?"inactive":"active"}'),
  @('Fechar ${kind === "alerts" ? "alertas" : "eventos"} do sender', 'Close sender ${kind === "alerts" ? "alerts" : "events"}'),
  @('Fechar janela', 'Close window'),
  @('Fechar ${title.toLocaleLowerCase("en-US")}', 'Close ${title.toLocaleLowerCase("en-US")}'),
  @('Unidade de ${label}', '${label} unit'),
  @('Ativa', 'Active'),
  @('Inativa', 'Inactive'),
  @('Disable regra', 'Disable rule'),
  @('Enable regra', 'Enable rule'),
  @('Edit regra', 'Edit rule'),
  @('Executions recentes', 'Recent executions'),
  @('Um sender not pode ser selecionado mais de uma vez.', 'A sender cannot be selected more than once.'),
  @('Alerta not encontrado.', 'Alert not found.'),
  @('Configure e habilite um e-mail antes de ativar o alerta.', 'Configure and enable email before enabling the alert.'),
  @('Email de teste enviado.', 'Test email sent.'),
  @('Informe o estado do alerta.', 'Provide the alert state.'),
  @('Limite de streams atingido', 'Stream limit reached'),
  @('Evento not encontrado.', 'Event not found.'),
  @('Rule de monitoramento not encontrada.', 'Monitoring rule not found.'),
  @('Informe um prazo entre 1 e 3.650 days.', 'Enter a period between 1 and 3,650 days.'),
  @('Complete as credenciais e o remetente antes de habilitar o Outlook.', 'Complete the credentials and sender before enabling Outlook.'),
  @('Configure EMAIL_SETTINGS_ENCRYPTION_KEY para salvar a credencial pela interface.', 'Configure EMAIL_SETTINGS_ENCRYPTION_KEY to save the credential through the interface.'),
  @('Configure EMAIL_SETTINGS_ENCRYPTION_KEY para salvar a senha pela interface.', 'Configure EMAIL_SETTINGS_ENCRYPTION_KEY to save the password through the interface.'),
  @('O Gmail recusou o remetente configurado.', 'Gmail rejected the configured sender.'),
  @('O servidor SMTP do Gmail not respondeu dentro do tempo esperado.', 'The Gmail SMTP server did not respond within the expected time.'),
  @('A mailbox remetente not foi encontrada no Microsoft 365. Confirme o e-mail e se ele possui uma caixa do Exchange Online.', 'The sender mailbox was not found in Microsoft 365. Confirm the email address and that it has an Exchange Online mailbox.'),
  @('O Microsoft 365 not respondeu dentro do tempo esperado.', 'Microsoft 365 did not respond within the expected time.'),
  @('O Outlook recusou o envio (HTTP %d).', 'Outlook rejected delivery (HTTP %d).'),
  @('A chave do evento not pode ser alterada.', 'The event key cannot be changed.'),
  @('A regra de monitoramento foi atendida.', 'The monitoring rule matched.'),
  @('Monitoramento: ', 'Monitoring: '),
  @('a mensagem ', 'the message '),
  @('A mensagem deve possuir entre 1 e 10.000 caracteres.', 'The message must be between 1 and 10,000 characters.'),
  @('Adicione um gatilho positivo de log, evento ou alerta.', 'Add a positive log, event, or alert trigger.'),
  @('"ativo"', '"active"'),
  @('"inativo"', '"inactive"'),
  @('"disparar um evento"', '"trigger an event"'),
  @('"enviar um e-mail"', '"send an email"'),
  @('limite de profundidade atingido', 'depth limit reached'),
  @('o alerta selecionado is triggered', 'the selected alert is triggered'),
  @('o evento “', 'event “'),
  @('O rascunho excede o limite de senders.', 'The draft exceeds the sender limit.'),
  @('O sender not pertence ao escopo da regra.', 'The sender is outside the rule scope.'),
  @('Select o status active ou inactive.', 'Select active or inactive status.'),
  @('Select um evento active.', 'Select an active event.'),
  @('Um sender selecionado not existe.', 'A selected sender does not exist.'),
  @('severity in [todas as severities]', 'severity in [all severities]'),
  @('Failed desconhecida no envio.', 'Unknown delivery failure.'),
  @('ALERTA DE LOG', 'LOG ALERT'),
  @('Esta mensagem confirma que o LogHill conseguiu autenticar e enviar e-mails pelo Gmail via SMTP.', 'This message confirms that LogHill successfully authenticated and sent email through Gmail via SMTP.'),
  @('Esta mensagem confirma que o LogHill conseguiu autenticar e enviar e-mails pelo Microsoft 365.', 'This message confirms that LogHill successfully authenticated and sent email through Microsoft 365.'),
  @('EVENTO DO LOG', 'LOG EVENT'),
  @('Inativo', 'Inactive'),
  @('Log do sistema registrado', 'System log recorded'),
  @('Novo log do sistema registrado', 'New system log recorded'),
  @('Novo rastreamento registrado', 'New trace recorded'),
  @('O evento “%s” foi informado explicitamente pelo sender.', 'Event “%s” was explicitly reported by the sender.'),
  @('SMTP com STARTTLS', 'SMTP with STARTTLS'),
  @('TESTE DE ALERTA', 'ALERT TEST'),
  @('TESTE DE E-MAIL', 'EMAIL TEST'),
  @('TESTE DE EVENTO', 'EVENT TEST'),
  @('Teste do LogHill', 'LogHill test'),
  @('Tudo certo com o seu e-mail', 'Your email is ready'),
  @('Mensagem de teste do alerta de e-mail do LogHill.', 'LogHill email alert test message.'),
  @('O nome deve possuir entre 3 e 80 caracteres.', 'The name must be between 3 and 80 characters.'),
  @('is not disparado', 'is not triggered'),
  @('Select o status ativo ou inativo.', 'Select active or inactive status.'),
  @('Select um evento ativo.', 'Select an active event.'),
  @('Estthe message confirma que o LogHill conseguiu autenticar e enviar e-mails pelo Gmail via SMTP.', 'This message confirms that LogHill successfully authenticated and sent email through Gmail via SMTP.'),
  @('Estthe message confirma que o LogHill conseguiu autenticar e enviar e-mails pelo Microsoft 365.', 'This message confirms that LogHill successfully authenticated and sent email through Microsoft 365.'),
  @('Select ao menos uma severidade.', 'Select at least one severity.'),
  @('Logo do ${label}', '${label} logo'),
  @('Ao vivo', 'Live'),
  @('Message do log', 'Log message'),
  @('Logo do ${outlook ? "Outlook" : "Gmail"}', '${outlook ? "Outlook" : "Gmail"} logo'),
  @('App password do Google', 'Google app password'),
  @('Informe um value entre 0 e 10.000.', 'Enter a value between 0 and 10,000.'),
  @('Informe um value entre ${minimum.toLocaleString("en-US")} e ${maximum.toLocaleString("en-US")} ${unit}.', 'Enter a value between ${minimum.toLocaleString("en-US")} and ${maximum.toLocaleString("en-US")} ${unit}.'),
  @('Instance do sender', 'Sender instance'),
  @('Pause os logs em tempo real', 'Pause live logs'),
  @('Informe um tempo entre 1 e 86.400 seconds.', 'Enter a duration between 1 and 86,400 seconds.'),
  @('Informe um value entre 0 e %s.', 'Enter a value between 0 and %s.'),
  @('O servidor SMTP not oferece STARTTLS.', 'The SMTP server does not offer STARTTLS.'),
  @('O Microsoft 365 limitou temporariamente os envios. Aguarde alguns instantes e tente novamente.', 'Microsoft 365 temporarily throttled deliveries. Wait a few moments and try again.'),
  @('o dia da semana ', 'the weekday '),
  @('o sender becomes ', 'the sender becomes '),
  @('Senders expirados ou revogados not podem ser monitorados.', 'Expired or revoked senders cannot be monitored.'),
  @('Um grupo not pode becomes vazio.', 'A group cannot be empty.'),
  @('Abrir logs do sender', 'Open sender logs'),
  @('Abrir o LogHill', 'Open LogHill'),
  @('Um erro foi detectado', 'An error was detected'),
  @('MENSAGEM', 'MESSAGE'),
  @('Provedor', 'Provider'),
  @('+{value.length - visible.length} selecionados', '+{value.length - visible.length} selected'),
  @('{value.length} selecionado{value.length === 1 ? "" : "s"}', '{value.length} selected'),
  @('Buscar senders', 'Search senders'),
  @('Nenhum envio', 'No deliveries'),
  @('Alert ativo', 'Active alert'),
  @('Rules inactive permanecem salvas sem enviar mensagens.', 'Inactive rules remain saved without sending messages.'),
  @('<code>chave</code>', '<code>key</code>'),
  @('Marque para associar e desmarque para remover este sender.', 'Select to associate and clear to remove this sender.'),
  @('Biblioteca de blocos', 'Block library'),
  @('Arraste ou clique para adicionar', 'Drag or click to add'),
  @('Ocultar', 'Hide'),
  @('Nenhuma chave precisa ser configurada no cliente. Use o identificador abaixo como', 'No key needs to be configured in the client. Use the identifier below as'),
  @('Logo do ', 'Logo for '),
  @('resposta inválida', 'invalid response')
)

$roots = @('frontend/src', 'internal', 'cmd')
$files = foreach ($root in $roots) {
  Get-ChildItem -LiteralPath $root -Recurse -File | Where-Object { $_.Extension -in '.ts', '.tsx', '.go', '.html', '.txt' }
}
$utf8 = [Text.UTF8Encoding]::new($false)
foreach ($file in $files) {
  $text = [IO.File]::ReadAllText($file.FullName)
  $updated = $text
  foreach ($pair in $pairs) { $updated = $updated.Replace($pair[0], $pair[1]) }
  if ($updated -ne $text) { [IO.File]::WriteAllText($file.FullName, $updated, $utf8) }
}
