import type { MonitoringAction, MonitoringCondition, MonitoringRuleInput } from "../../types/monitoring";

export type BlockCategory = "trigger" | "condition" | "action";
export interface MonitoringBlock { id: string; category: BlockCategory; type: string; connector: "and" | "or"; negated: boolean; condition?: MonitoringCondition; action?: MonitoringAction }
export type LibraryBlockType = "event_triggered"|"alert_triggered"|"sender_status"|"log_received"|"message"|"severity"|"metadata"|"time"|"weekday"|"date"|"send_email"|"trigger_event";
export const temporaryID=()=>`temp_${crypto.randomUUID()}`;

const severities=["TRACE","DEBUG","INFO","WARN","ERROR","FATAL"];
export function createBlock(type:LibraryBlockType):MonitoringBlock { const id=temporaryID();if(type==="send_email")return{id,category:"action",type,connector:"and",negated:false,action:{id,type:"send_email",config:{recipients:[],subject:"Monitoramento: {{rule.name}}",message:"A regra {{rule.name}} foi atendida para {{sender.name}}."}}};if(type==="trigger_event")return{id,category:"action",type,connector:"and",negated:false,action:{id,type:"trigger_event",config:{event_id:"",message:"Regra de monitoramento atendida",severity:"INFO"}}};if(type==="log_received")return{id,category:"trigger",type,connector:"and",negated:false,condition:{id,type:"severity",operator:"in",value:{severities,source:"log_received"},negated:false}};const defaults:Record<string,{operator:string;value:Record<string,unknown>}>= {event_triggered:{operator:"triggered",value:{event_key:"",window_minutes:0}},alert_triggered:{operator:"triggered",value:{alert_id:"",window_minutes:0}},sender_status:{operator:"became",value:{status:"online"}},message:{operator:"contains",value:{text:""}},severity:{operator:"equals",value:{severity:"ERROR"}},metadata:{operator:"exists",value:{path:"",value:""}},time:{operator:"between",value:{start:"12:00",end:"17:00"}},weekday:{operator:"equals",value:{weekday:"monday"}},date:{operator:"between",value:{start:"",end:""}}};const value=defaults[type];return{id,category:type==="event_triggered"||type==="alert_triggered"||type==="sender_status"?"trigger":"condition",type,connector:"and",negated:false,condition:{id,type:type as MonitoringCondition["type"],operator:value.operator,value:value.value,negated:false}} }

function isLogReceived(condition:MonitoringCondition,index:number){const values=condition.value.severities;return index===0&&condition.type==="severity"&&condition.operator==="in"&&(condition.value.source==="log_received"||(Array.isArray(values)&&severities.every(value=>values.includes(value))))}
export function fromRule(rule:MonitoringRuleInput):MonitoringBlock[]{const conditions=rule.expression.nodes.flatMap((node,index)=>node.condition?[{id:node.condition.id??temporaryID(),category:index===0?"trigger" as const:"condition" as const,type:isLogReceived(node.condition,index)?"log_received":node.condition.type,connector:node.connector??"and",negated:node.condition.negated,condition:{...node.condition}}]:[]);const actions=rule.actions.map(action=>({id:action.id??temporaryID(),category:"action" as const,type:action.type,connector:"and" as const,negated:false,action:{...action}}));return [...conditions,...actions]}
export function toRule(blocks:MonitoringBlock[],base:Omit<MonitoringRuleInput,"expression"|"actions">):MonitoringRuleInput { const logical=blocks.filter(block=>block.condition).map(block=>({connector:block.connector,condition:{...block.condition!,id:block.id,negated:block.negated}}));const actions=blocks.filter(block=>block.action).map(block=>({...block.action!,id:block.id}));return{...base,expression:{operator:"and",negated:false,nodes:logical},actions} }
export function blockRank(block:MonitoringBlock){return block.category==="trigger"?0:block.category==="condition"?1:2}
export function validOrder(blocks:MonitoringBlock[]){let rank=-1,triggers=0;for(const block of blocks){const next=blockRank(block);if(next<rank)return false;rank=next;if(block.category==="trigger")triggers++}return triggers===1&&blocks[0]?.category==="trigger"}
export function insertBlock(blocks:MonitoringBlock[],block:MonitoringBlock,index?:number){const next=[...blocks];if(block.category==="trigger"){if(next.some(item=>item.category==="trigger"))return{blocks,message:"A regra já possui um gatilho inicial."};next.unshift(block);return{blocks:next,message:""}};if(block.category==="condition"){if(!next.some(item=>item.category==="trigger"))return{blocks,message:"Adicione um gatilho antes das condições."};const firstAction=next.findIndex(item=>item.category==="action");const maximum=firstAction<0?next.length:firstAction;next.splice(Math.max(1,Math.min(index??maximum,maximum)),0,block);return{blocks:next,message:""}};if(!next.some(item=>item.category==="trigger"))return{blocks,message:"Adicione um gatilho antes das ações."};next.push(block);return{blocks:next,message:""}}
export function moveBlock(blocks:MonitoringBlock[],from:number,to:number){if(from<0||to<0||from>=blocks.length||to>=blocks.length)return{blocks,message:"Posição inválida."};const next=[...blocks];const [block]=next.splice(from,1);next.splice(to,0,block);if(!validOrder(next))return{blocks,message:block.category==="action"?"Ações devem permanecer depois das condições.":"Gatilhos e condições devem permanecer antes das ações."};return{blocks:next,message:""}}
export function blockProblem(block:MonitoringBlock){if(block.category==="trigger"&&block.type==="event_triggered"&&!block.condition?.value.event_key)return"Selecione um evento.";if(block.category==="trigger"&&block.type==="alert_triggered"&&!block.condition?.value.alert_id)return"Selecione um alerta.";if(block.type==="message"&&!String(block.condition?.value.text??"").trim())return"Informe o texto que deverá ser buscado.";if(block.type==="metadata"&&!String(block.condition?.value.path??"").trim())return"Informe o caminho da metadata.";if(block.type==="trigger_event"&&!block.action?.config.event_id)return"Selecione um evento de destino.";if(block.type==="send_email"&&(!Array.isArray(block.action?.config.recipients)||!block.action?.config.recipients.length))return"Selecione pelo menos um destinatário.";return""}
export function validateBlocks(blocks:MonitoringBlock[]){const problems=new Map<string,string>();if(!blocks.some(b=>b.category==="trigger"))problems.set("structure","Adicione um gatilho inicial.");if(!blocks.some(b=>b.category==="action"))problems.set("actions","Adicione uma ação.");for(const block of blocks){const problem=blockProblem(block);if(problem)problems.set(block.id,problem)}return problems}
export function blockTitle(block:MonitoringBlock){const names:Record<string,string>={event_triggered:"Evento disparado",alert_triggered:"Alerta disparado",sender_status:"Status do sender",log_received:"Log recebido",message:"Mensagem do log",severity:"Severity",metadata:"Metadata",time:"Horário",weekday:"Dia da semana",date:"Data",send_email:"Enviar e-mail",trigger_event:"Disparar evento"};return names[block.type]??block.type}
export function blockSummary(block:MonitoringBlock){const value=block.condition?.value??block.action?.config??{};switch(block.type){case"event_triggered":return`Evento “${value.event_key||"não selecionado"}” ${block.condition?.operator.replaceAll("_"," ")}`;case"alert_triggered":return`Alerta ${value.alert_id||"não selecionado"} ${block.condition?.operator.replaceAll("_"," ")}`;case"sender_status":return`Quando ficar ${value.status==="inactive"?"inativo":"ativo"}`;case"log_received":return"Quando qualquer log for recebido";case"message":return`Mensagem ${block.condition?.operator.replaceAll("_"," ")} “${value.text||"…"}”`;case"severity":return`Severity ${block.condition?.operator.replaceAll("_"," ")} ${value.severity||"…"}`;case"metadata":return`Metadata ${value.path||"…"} ${block.condition?.operator.replaceAll("_"," ")}`;case"time":return`Horário ${block.condition?.operator.replaceAll("_"," ")} ${value.start||"…"}${value.end?` e ${value.end}`:""}`;case"weekday":return`Dia da semana ${block.condition?.operator.replaceAll("_"," ")} ${value.weekday||"…"}`;case"date":return`Data ${block.condition?.operator.replaceAll("_"," ")} ${value.start||"…"}`;case"send_email":return`Enviar e-mail para ${Array.isArray(value.recipients)&&value.recipients.length?value.recipients.join(", "):"destinatários não definidos"}`;case"trigger_event":return`Disparar o evento ${value.event_id||"não selecionado"}`;default:return blockTitle(block)}}
