import type { MonitoringAction, MonitoringCondition, MonitoringRuleInput } from "../../types/monitoring";

export type BlockCategory = "trigger" | "condition" | "action";
export interface MonitoringBlock { id: string; category: BlockCategory; type: string; connector: "and" | "or"; negated: boolean; condition?: MonitoringCondition; action?: MonitoringAction }
export type LibraryBlockType = "event_triggered"|"alert_triggered"|"sender_status"|"log_received"|"message"|"severity"|"metadata"|"time"|"weekday"|"date"|"send_email"|"trigger_event";
export const temporaryID=()=>`temp_${crypto.randomUUID()}`;

const legacySeverities=["TRACE","DEBUG","INFO","WARN","ERROR","FATAL"];
export function createBlock(type:LibraryBlockType):MonitoringBlock { const id=temporaryID();if(type==="send_email")return{id,category:"action",type,connector:"and",negated:false,action:{id,type:"send_email",config:{recipients:[],subject:"Monitoring: {{rule.name}}",message:"Rule {{rule.name}} matched for {{sender.name}}."}}};if(type==="trigger_event")return{id,category:"action",type,connector:"and",negated:false,action:{id,type:"trigger_event",config:{event_id:"",message:"Monitoring rule matched",severity:"INFO"}}};if(type==="log_received")return{id,category:"trigger",type,connector:"and",negated:false,condition:{id,type:"log_received",operator:"received",value:{},negated:false}};const defaults:Record<string,{operator:string;value:Record<string,unknown>}>= {event_triggered:{operator:"triggered",value:{event_key:"",window_minutes:0}},alert_triggered:{operator:"triggered",value:{alert_id:"",window_minutes:0}},sender_status:{operator:"became",value:{status:"online"}},message:{operator:"contains",value:{text:""}},severity:{operator:"equals",value:{severity:"ERROR"}},metadata:{operator:"exists",value:{path:"",value:""}},time:{operator:"between",value:{start:"12:00",end:"17:00"}},weekday:{operator:"equals",value:{weekday:"monday"}},date:{operator:"between",value:{start:"",end:""}}};const value=defaults[type];return{id,category:type==="event_triggered"||type==="alert_triggered"||type==="sender_status"?"trigger":"condition",type,connector:"and",negated:false,condition:{id,type:type as MonitoringCondition["type"],operator:value.operator,value:value.value,negated:false}} }

function isLogReceived(condition:MonitoringCondition,index:number){if(condition.type==="log_received")return true;const values=condition.value.severities;return index===0&&condition.type==="severity"&&condition.operator==="in"&&(condition.value.source==="log_received"||(Array.isArray(values)&&legacySeverities.every(value=>values.includes(value))))}
function logReceivedCondition(id:string):MonitoringCondition{return{id,type:"log_received",operator:"received",value:{},negated:false}}
export function fromRule(rule:MonitoringRuleInput):MonitoringBlock[]{const conditions=rule.expression.nodes.flatMap((node,index)=>{if(!node.condition)return [];const id=node.condition.id??temporaryID();const logReceived=isLogReceived(node.condition,index);return [{id,category:index===0?"trigger" as const:"condition" as const,type:logReceived?"log_received":node.condition.type,connector:node.connector??"and",negated:node.condition.negated,condition:logReceived?logReceivedCondition(id):{...node.condition}}]});const actions=rule.actions.map(action=>({id:action.id??temporaryID(),category:"action" as const,type:action.type,connector:"and" as const,negated:false,action:{...action}}));return [...conditions,...actions]}
export function toRule(blocks:MonitoringBlock[],base:Omit<MonitoringRuleInput,"expression"|"actions">):MonitoringRuleInput { const logical=blocks.filter(block=>block.condition).map(block=>({connector:block.connector,condition:{...block.condition!,id:block.id,negated:block.negated}}));const actions=blocks.filter(block=>block.action).map(block=>({...block.action!,id:block.id}));return{...base,expression:{operator:"and",negated:false,nodes:logical},actions} }
export function blockRank(block:MonitoringBlock){return block.category==="trigger"?0:block.category==="condition"?1:2}
export function validOrder(blocks:MonitoringBlock[]){let rank=-1,triggers=0;for(const block of blocks){const next=blockRank(block);if(next<rank)return false;rank=next;if(block.category==="trigger")triggers++}return triggers===1&&blocks[0]?.category==="trigger"}
export function insertBlock(blocks:MonitoringBlock[],block:MonitoringBlock,index?:number){const next=[...blocks];if(block.category==="trigger"){if(next.some(item=>item.category==="trigger"))return{blocks,message:"The rule already has an initial trigger."};next.unshift(block);return{blocks:next,message:""}};if(block.category==="condition"){if(!next.some(item=>item.category==="trigger"))return{blocks,message:"Add a trigger before conditions."};const firstAction=next.findIndex(item=>item.category==="action");const maximum=firstAction<0?next.length:firstAction;next.splice(Math.max(1,Math.min(index??maximum,maximum)),0,block);return{blocks:next,message:""}};if(!next.some(item=>item.category==="trigger"))return{blocks,message:"Add a trigger before actions."};next.push(block);return{blocks:next,message:""}}
export function moveBlock(blocks:MonitoringBlock[],from:number,to:number){if(from<0||to<0||from>=blocks.length||to>=blocks.length)return{blocks,message:"Invalid position."};const next=[...blocks];const [block]=next.splice(from,1);next.splice(to,0,block);if(!validOrder(next))return{blocks,message:block.category==="action"?"Actions must remain after conditions.":"Triggers and conditions must remain before actions."};return{blocks:next,message:""}}
export function blockProblem(block:MonitoringBlock){if(block.category==="trigger"&&block.type==="event_triggered"&&!block.condition?.value.event_key)return"Select an event.";if(block.category==="trigger"&&block.type==="alert_triggered"&&!block.condition?.value.alert_id)return"Select an alert.";if(block.type==="message"&&!String(block.condition?.value.text??"").trim())return"Enter the text to search for.";if(block.type==="metadata"&&!String(block.condition?.value.path??"").trim())return"Enter the metadata path.";if(block.type==="trigger_event"&&!block.action?.config.event_id)return"Select a target event.";if(block.type==="send_email"&&(!Array.isArray(block.action?.config.recipients)||!block.action?.config.recipients.length))return"Select at least one recipient.";return""}
export function validateBlocks(blocks:MonitoringBlock[]){const problems=new Map<string,string>();if(!blocks.some(b=>b.category==="trigger"))problems.set("structure","Add an initial trigger.");if(!blocks.some(b=>b.category==="action"))problems.set("actions","Add an action.");for(const block of blocks){const problem=blockProblem(block);if(problem)problems.set(block.id,problem)}return problems}
export function blockTitle(block:MonitoringBlock){const names:Record<string,string>={event_triggered:"Event triggered",alert_triggered:"Alert triggered",sender_status:"Sender status",log_received:"Log received",message:"Log message",severity:"Severity",metadata:"Metadata",time:"Time",weekday:"Weekday",date:"Date",send_email:"Send email",trigger_event:"Trigger event"};return names[block.type]??block.type}
export function blockSummary(block:MonitoringBlock){const value=block.condition?.value??block.action?.config??{};switch(block.type){case"event_triggered":return`Event “${value.event_key||"not selected"}” ${block.condition?.operator.replaceAll("_"," ")}`;case"alert_triggered":return`Alert ${value.alert_id||"not selected"} ${block.condition?.operator.replaceAll("_"," ")}`;case"sender_status":return`When it becomes ${value.status==="inactive"?"inactive":"active"}`;case"log_received":return"When any log is received";case"message":return`Message ${block.condition?.operator.replaceAll("_"," ")} “${value.text||"…"}”`;case"severity":return`Severity ${block.condition?.operator.replaceAll("_"," ")} ${value.severity||"…"}`;case"metadata":return`Metadata ${value.path||"…"} ${block.condition?.operator.replaceAll("_"," ")}`;case"time":return`Time ${block.condition?.operator.replaceAll("_"," ")} ${value.start||"…"}${value.end?` and ${value.end}`:""}`;case"weekday":return`Weekday ${block.condition?.operator.replaceAll("_"," ")} ${value.weekday||"…"}`;case"date":return`Date ${block.condition?.operator.replaceAll("_"," ")} ${value.start||"…"}`;case"send_email":return`Send email to ${Array.isArray(value.recipients)&&value.recipients.length?value.recipients.join(", "):"recipients not defined"}`;case"trigger_event":return`Trigger event ${value.event_id||"not selected"}`;default:return blockTitle(block)}}
