import { Edit3, Eye, Mail, Power, Radar, Send, Trash2 } from "lucide-react";
import type { EventDefinition } from "../../types/event";
import { relativeDate } from "../../utils/format";
import { IconButton } from "../ui";
import { EventStatusBadge } from "./EventStatusBadge";

interface Props { items: EventDefinition[]; busyId: string; onDetails: (event: EventDefinition) => void; onEdit: (event: EventDefinition) => void; onToggle: (event: EventDefinition) => void; onTest: (event: EventDefinition) => void; onDelete: (event: EventDefinition) => void }

function Actions({ event, props }: { event: EventDefinition; props: Props }) { const busy = props.busyId === event.id; return <div className="flex justify-end gap-0.5"><IconButton label="Ver detalhes" className="size-7" disabled={busy} onClick={() => props.onDetails(event)}><Eye className="size-3.5" /></IconButton><IconButton label="Editar evento" className="size-7" disabled={busy} onClick={() => props.onEdit(event)}><Edit3 className="size-3.5" /></IconButton><IconButton label={event.enabled ? "Desativar evento" : "Ativar evento"} className="size-7" disabled={busy} onClick={() => props.onToggle(event)}><Power className="size-3.5" /></IconButton>{event.actionType === "email" && <IconButton label="Enviar teste" className="size-7" disabled={busy} onClick={() => props.onTest(event)}><Send className="size-3.5" /></IconButton>}<IconButton label="Excluir evento" className="size-7 text-red-400" disabled={busy} onClick={() => props.onDelete(event)}><Trash2 className="size-3.5" /></IconButton></div>; }

export function EventTable(props: Props) {
  return <div className="min-h-52"><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[940px] table-fixed text-left text-xs"><thead className="sticky top-0 z-10 bg-[#1c1c1f] text-zinc-500"><tr className="h-10 border-b border-zinc-800"><th className="w-24 px-3 font-medium">Status</th><th className="w-[20%] px-3 font-medium">Evento</th><th className="w-[20%] px-3 font-medium">Chave</th><th className="w-24 px-3 font-medium">Senders</th><th className="w-24 px-3 font-medium">Ação</th><th className="w-32 px-3 font-medium">Última execução</th><th className="w-40 px-2 text-right font-medium">Ações</th></tr></thead><tbody className="divide-y divide-zinc-800/80">{props.items.map((event) => <tr key={event.id} className="h-12 hover:bg-zinc-900/50"><td className="px-3"><EventStatusBadge enabled={event.enabled} /></td><td className="min-w-0 px-3"><button type="button" onClick={() => props.onDetails(event)} className="block max-w-full truncate font-medium text-zinc-200 hover:text-white hover:underline focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-white/50" title={event.name}>{event.name}</button></td><td className="px-3"><code className="block truncate text-[10px] text-zinc-400" title={event.key}>{event.key}</code></td><td className="px-3 text-zinc-400">{event.senderIds.length} sender{event.senderIds.length === 1 ? "" : "s"}</td><td className="px-3"><span className="inline-flex items-center gap-1.5 text-zinc-400">{event.actionType === "email" ? <><Mail className="size-3.5"/>E-mail</> : <><Radar className="size-3.5"/>Monitoramento</>}</span></td><td className="px-3 text-zinc-500" title={event.lastTriggeredAt}>{event.lastTriggeredAt ? relativeDate(event.lastTriggeredAt) : "Nunca"}</td><td className="px-2"><Actions event={event} props={props} /></td></tr>)}</tbody></table></div><div className="divide-y divide-zinc-800 md:hidden">{props.items.map((event) => <article key={event.id} className="p-3"><div className="flex items-start justify-between gap-3"><button type="button" onClick={() => props.onDetails(event)} className="min-w-0 truncate text-left text-sm font-medium text-zinc-200">{event.name}</button><EventStatusBadge enabled={event.enabled} /></div><code className="mt-1 block truncate text-[10px] text-zinc-500">{event.key}</code><div className="mt-2 flex justify-between text-[10px] text-zinc-500"><span>{event.senderIds.length} sender{event.senderIds.length === 1 ? "" : "s"}</span><span>{event.lastTriggeredAt ? relativeDate(event.lastTriggeredAt) : "Nunca executado"}</span></div><div className="mt-2 border-t border-zinc-800 pt-2"><Actions event={event} props={props} /></div></article>)}</div></div>;
}
