import { ExternalLink, Zap } from "lucide-react";

const example: Record<string, string> = { "event.key": "processing_completed", "event.name": "Processing completed", "sender.id": "financial-automation", "sender.name": "Financial Automation", "sender.status": "Online", "log.message": "Processing completed successfully.", "log.severity": "INFO", "log.timestamp": new Date().toISOString(), "app.public_url": window.location.origin, "metadata.protocol": "ABC-123", "metadata.recipient": "customer@company.com", "metadata.key": "sample value" };

function renderPreview(value: string) { return value.replace(/{{\s*([^{}]+?)\s*}}/g, (_, key: string) => example[key.trim()] ?? ""); }

export function EventTemplatePreview({ name, eventKey, subject, message }: { name: string; eventKey: string; subject: string; message: string }) {
  return <section aria-label="Email preview" className="overflow-hidden rounded-xl border border-zinc-700 bg-[#09090b]"><div className="border-b border-zinc-800 bg-[#161618] px-4 py-3"><p className="text-[10px] uppercase tracking-wide text-zinc-600">Email preview</p><p className="mt-1 truncate text-sm font-medium text-zinc-200">{renderPreview(subject) || "Event subject"}</p></div><div className="p-4"><div className="flex items-center gap-2 text-[10px] font-medium uppercase tracking-wider text-amber-500"><Zap className="size-3.5" />LogMate event</div><h3 className="mt-3 text-lg font-semibold text-zinc-100">{name || "Event name"}</h3><p className="mt-1 font-mono text-[10px] text-zinc-600">{eventKey || "event_key"}</p><div className="mt-4 whitespace-pre-wrap break-words rounded-lg border border-zinc-800 bg-zinc-950 p-4 text-sm leading-6 text-zinc-300">{renderPreview(message) || "The custom message will appear here."}</div><dl className="mt-4 grid grid-cols-2 gap-3 text-[10px]"><div><dt className="text-zinc-600">Sender</dt><dd className="mt-1 text-zinc-300">Financial Automation</dd></div><div><dt className="text-zinc-600">Severity</dt><dd className="mt-1 text-zinc-300">INFO</dd></div><div className="col-span-2"><dt className="text-zinc-600">Timestamp</dt><dd className="mt-1 text-zinc-300">{new Date().toLocaleString("en-US")}</dd></div></dl><span className="mt-5 inline-flex h-9 items-center gap-2 rounded bg-amber-500 px-4 text-xs font-semibold text-zinc-950">Open sender logs<ExternalLink className="size-3.5" /></span></div></section>;
}
