import { Send } from "lucide-react";
import { useEffect, useId, useState } from "react";
import { createPortal } from "react-dom";
import { eventsApi } from "../../api/events";
import type { EventDefinition } from "../../types/event";
import { Button, Input, ModalCloseButton } from "../ui";

const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

export function EventTestDialog({ event, onClose, onSent }: { event?: EventDefinition; onClose: () => void; onSent: () => void }) { const titleId = useId(); const [recipient, setRecipient] = useState(""); const [sending, setSending] = useState(false); const [error, setError] = useState(""); useEffect(() => { if (!event) { setRecipient(""); setError(""); } }, [event]); if (!event) return null; const send = async () => { if (!emailPattern.test(recipient) || sending) { setError("Informe um destinatário válido."); return; } setSending(true); setError(""); try { await eventsApi.sendTest(event.id, recipient); onSent(); onClose(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Não foi possível enviar o teste."); } finally { setSending(false); } }; return createPortal(<div className="fixed inset-0 z-[225] grid place-items-center p-4"><button type="button" aria-label="Fechar teste" onClick={() => !sending && onClose()} className="absolute inset-0 bg-black/75" /><div role="dialog" aria-modal="true" aria-labelledby={titleId} className="relative w-full max-w-md rounded-xl border border-zinc-700 bg-[#161618] p-5 shadow-2xl"><div className="flex justify-between gap-4"><div><h2 id={titleId} className="text-base font-semibold text-zinc-100">Enviar teste</h2><p className="mt-1 text-xs leading-5 text-zinc-500">Usa o template de “{event.name}” com dados fictícios. O teste não conta como execução real.</p></div><ModalCloseButton label="Fechar teste do evento" disabled={sending} onClick={onClose} /></div><label className="mt-5 block text-xs font-medium text-zinc-300">Destinatário<Input autoFocus type="email" value={recipient} onChange={(change) => { setRecipient(change.target.value); setError(""); }} onKeyDown={(keyboard) => { if (keyboard.key === "Enter") void send(); }} placeholder="usuario@empresa.com" className="mt-2 w-full" /></label>{error && <p role="alert" className="mt-3 rounded-lg border border-red-950 bg-red-950/20 px-3 py-2 text-xs text-red-300">{error}</p>}<div className="mt-5 flex justify-end gap-2"><Button onClick={onClose} disabled={sending} className="border-transparent bg-transparent">Cancelar</Button><Button onClick={() => void send()} disabled={sending || !emailPattern.test(recipient)}><Send className="size-4" />{sending ? "Enfileirando..." : "Enviar teste"}</Button></div></div></div>, document.body); }
