import { useEffect, useState } from "react";
import { executionsApi } from "../../api/executions";
import type { ExecutionRecord, ExecutionSourceType } from "../../types/execution";
import { useCachedState } from "../../hooks/useCachedState";
import { Skeleton } from "../ui";
import { ExecutionDetailsDrawer } from "./ExecutionView";
import { ExecutionStatusBadge } from "./ExecutionStatusBadge";

const paths:Record<ExecutionSourceType,string>={alert:"/alerts",event:"/events",monitoring:"/monitoring"};
export function SourceRecentExecutions({source,sourceID}:{source:ExecutionSourceType;sourceID:string}){const[items,setItems]=useCachedState<ExecutionRecord[]>(["view","source-executions",source,sourceID]);const[selected,setSelected]=useState<ExecutionRecord>();useEffect(()=>{let active=true;const query=new URLSearchParams({source_type:source,source_id:sourceID,page_size:"5"});void executionsApi.list(query.toString()).then(result=>{if(active)setItems(result.items)}).catch(()=>{});return()=>{active=false}},[source,sourceID]);return <section><div className="flex items-center justify-between"><h3 className="text-xs font-medium">Latest executions</h3><a href={`${paths[source]}?tab=executions&source_id=${encodeURIComponent(sourceID)}`} className="text-[10px] text-zinc-500 hover:text-zinc-200">View all executions</a></div><div className="mt-2 space-y-1.5">{items===undefined?<div className="space-y-1.5">{[1,2,3].map(item=><Skeleton key={item} className="h-10"/>)}</div>:items.length?items.map(item=><button key={item.id} onClick={()=>setSelected(item)} className="flex w-full items-center justify-between rounded-lg border border-zinc-800 p-2 text-left text-[11px] hover:bg-zinc-900"><span className="truncate">{new Date(item.started_at).toLocaleString("en-US")}</span><ExecutionStatusBadge status={item.status}/></button>):<p className="rounded-lg border border-zinc-800 p-3 text-[11px] text-zinc-600">No executions recorded.</p>}</div><ExecutionDetailsDrawer record={selected} onClose={()=>setSelected(undefined)}/></section>}
