package config

import (
	"encoding/base64"
	"os"
	"path/filepath"
	"testing"
)

func TestO365EnvironmentAliases(t *testing.T) {
	t.Setenv("DATA_DIR", t.TempDir())
	t.Setenv("EMAIL_PROVIDER", "o365")
	t.Setenv("OUTLOOK_ENABLED", "true")
	t.Setenv("OUTLOOK_TENANT_ID", "")
	t.Setenv("OUTLOOK_CLIENT_ID", "")
	t.Setenv("OUTLOOK_CLIENT_SECRET", "")
	t.Setenv("OUTLOOK_SENDER_EMAIL", "")
	t.Setenv("O365_TENANT_ID", "legacy-tenant")
	t.Setenv("O365_CLIENT_ID", "legacy-client")
	t.Setenv("O365_CLIENT_SECRET", "legacy-secret")
	t.Setenv("EMAIL_FROM_ADDR", "logs@example.com")
	t.Setenv("APP_PASSWORD", "")
	t.Setenv("ADMIN_API_KEY", "")
	t.Setenv("ADMIN_AUTH_ENABLED", "false")
	t.Setenv("EMAIL_SETTINGS_ENCRYPTION_KEY", "")
	cfg, err := Load()
	if err != nil {
		t.Fatal(err)
	}
	if cfg.EmailProvider != "outlook" || cfg.OutlookTenantID != "legacy-tenant" || cfg.OutlookClientID != "legacy-client" || cfg.OutlookClientSecret != "legacy-secret" || cfg.OutlookSenderEmail != "logs@example.com" || !cfg.OutlookEnabled {
		t.Fatalf("aliases not loaded: %+v", cfg)
	}
}

func TestPublicURLMustBeSafeAndAbsolute(t *testing.T) {
	t.Setenv("DATA_DIR", t.TempDir())
	t.Setenv("APP_PUBLIC_URL", "javascript:alert(1)")
	t.Setenv("APP_PASSWORD", "")
	t.Setenv("ADMIN_API_KEY", "")
	t.Setenv("ADMIN_AUTH_ENABLED", "false")
	if _, err := Load(); err == nil {
		t.Fatal("unsafe public URL should be rejected")
	}
}

func TestEncryptionKeyIsAutoGeneratedAndPersisted(t *testing.T) {
	dataDir := t.TempDir()
	t.Setenv("DATA_DIR", dataDir)
	t.Setenv("EMAIL_SETTINGS_ENCRYPTION_KEY", "")
	t.Setenv("APP_PASSWORD", "")
	t.Setenv("ADMIN_API_KEY", "")
	t.Setenv("ADMIN_AUTH_ENABLED", "false")
	t.Setenv("APP_PUBLIC_URL", "http://localhost:8080")

	first, err := Load()
	if err != nil {
		t.Fatal(err)
	}
	decoded, err := base64.StdEncoding.DecodeString(first.EmailSettingsEncryptionKey)
	if err != nil || len(decoded) != 32 {
		t.Fatalf("auto-generated key is invalid: %q", first.EmailSettingsEncryptionKey)
	}
	persisted, err := os.ReadFile(filepath.Join(dataDir, emailEncryptionKeyFile))
	if err != nil {
		t.Fatal(err)
	}
	if got := string(persisted); got != first.EmailSettingsEncryptionKey+"\n" {
		t.Fatalf("persisted key mismatch: %q vs %q", got, first.EmailSettingsEncryptionKey)
	}

	t.Setenv("EMAIL_SETTINGS_ENCRYPTION_KEY", "invalid")
	second, err := Load()
	if err != nil {
		t.Fatal(err)
	}
	if second.EmailSettingsEncryptionKey != first.EmailSettingsEncryptionKey {
		t.Fatalf("invalid env should reuse persisted key: %q vs %q", second.EmailSettingsEncryptionKey, first.EmailSettingsEncryptionKey)
	}
}

func TestEncryptionKeyFromEnvWins(t *testing.T) {
	dataDir := t.TempDir()
	wanted := base64.StdEncoding.EncodeToString(make([]byte, 32))
	t.Setenv("DATA_DIR", dataDir)
	t.Setenv("EMAIL_SETTINGS_ENCRYPTION_KEY", wanted)
	t.Setenv("APP_PASSWORD", "")
	t.Setenv("ADMIN_API_KEY", "")
	t.Setenv("ADMIN_AUTH_ENABLED", "false")
	t.Setenv("APP_PUBLIC_URL", "http://localhost:8080")

	cfg, err := Load()
	if err != nil {
		t.Fatal(err)
	}
	if cfg.EmailSettingsEncryptionKey != wanted {
		t.Fatalf("env key should win: got %q want %q", cfg.EmailSettingsEncryptionKey, wanted)
	}
}

func TestAppPasswordEnablesAuth(t *testing.T) {
	t.Setenv("DATA_DIR", t.TempDir())
	t.Setenv("APP_PASSWORD", "secret-pass")
	_ = os.Unsetenv("ADMIN_API_KEY")
	_ = os.Unsetenv("ADMIN_AUTH_ENABLED")
	_ = os.Unsetenv("APP_AUTH_ENABLED")
	t.Setenv("APP_PUBLIC_URL", "http://localhost:8080")
	_ = os.Unsetenv("EMAIL_SETTINGS_ENCRYPTION_KEY")
	cfg, err := Load()
	if err != nil {
		t.Fatal(err)
	}
	if !cfg.AuthEnabled || cfg.AppPassword != "secret-pass" {
		t.Fatalf("auth should be enabled with APP_PASSWORD: %+v", cfg)
	}
}

func TestLoadDotEnvFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".env")
	content := "DOTENV_TEST_VALUE=from-file\nAPP_PUBLIC_URL=http://localhost:9090\n"
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
	cwd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err = os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(cwd) })

	t.Setenv("DATA_DIR", t.TempDir())
	t.Setenv("DOTENV_TEST_VALUE", "")
	_ = os.Unsetenv("DOTENV_TEST_VALUE")
	_ = os.Unsetenv("APP_PUBLIC_URL")
	t.Setenv("APP_PASSWORD", "")
	t.Setenv("ADMIN_API_KEY", "")
	t.Setenv("ADMIN_AUTH_ENABLED", "false")
	t.Setenv("EMAIL_SETTINGS_ENCRYPTION_KEY", "")

	cfg, err := Load()
	if err != nil {
		t.Fatal(err)
	}
	if os.Getenv("DOTENV_TEST_VALUE") != "from-file" {
		t.Fatalf("dotenv value not loaded: %q", os.Getenv("DOTENV_TEST_VALUE"))
	}
	if cfg.PublicURL != "http://localhost:9090" {
		t.Fatalf("public URL from dotenv not applied: %q", cfg.PublicURL)
	}
}
